const fs = require('fs');
const path = require('path');
const { sanitizeMathText } = require('./mathQuestionBankSanitizer');
const {
  buildImageMetadataMap,
  canonicalizeImageAssetPath,
  loadMergedImageMetadata,
} = require('./imageMetadataRepository');
const {
  classifyCoreQuestionQualityIssues,
  getQuestionImage,
  getQuestionPassage,
  getQuestionText,
  normalizeAnswerOptions,
} = require('./questionQualityCore');

const IMAGE_EXTENSIONS = new Set([
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.svg',
  '.webp',
]);

const PLACEHOLDER_PATTERNS = [
  /\bplaceholder\b/i,
  /\blorem\s+ipsum\b/i,
  /\btbd\b/i,
  /\bto\s*be\s*determined\b/i,
  /\bcoming\s+soon\b/i,
  /\bwrite\s+question\b/i,
  /\binsert\s+question\b/i,
  /\bsample\s+question\b/i,
  /\bfill\s+in\s+later\b/i,
  /\bautogenerated?\b/i,
  /\btemplate\b/i,
  // A "blank" of underscores (e.g. _____ in a cloze question) is legitimate
  // content; only flag underscore-only lines as placeholders.
  /^_{3,}$/,
  /\[\s*\.\.\.\s*\]/,
  /\{\s*\.\.\.\s*\}/,
];

const ISSUE_SEVERITY = {
  'duplicate-options': 'blocker',
  'duplicate-rationales': 'major',
  'embedded-choice-text': 'major',
  'generic-stem': 'major',
  'image-asset-missing': 'blocker',
  'image-metadata-missing': 'warning',
  'image-path-invalid': 'blocker',
  'invalid-correct-count': 'blocker',
  'logic-defect': 'blocker',
  'math-command-outside-delimiters': 'major',
  'math-latex-brace-unbalanced': 'blocker',
  'math-latex-dollar-delimiter': 'major',
  'math-latex-dollar-unbalanced': 'blocker',
  'math-latex-unbalanced': 'blocker',
  'math-plain-exponent-outside-delimiters': 'major',
  'math-plain-fraction-in-math': 'major',
  'math-plain-fraction-outside-delimiters': 'major',
  'missing-answer-rationale': 'blocker',
  'missing-answer-text': 'blocker',
  'missing-correct-answer': 'blocker',
  'missing-prompt': 'blocker',
  'missing-stimulus': 'blocker',
  'missing-stimulus-image': 'blocker',
  'missing-stimulus-passage': 'blocker',
  'missing-stimulus-table': 'blocker',
  'non-four-options': 'blocker',
  'placeholder-option': 'major',
  'placeholder-rationale': 'major',
  'science-thin-rationale': 'major',
  'short-correct-rationale': 'major',
  'short-question-text': 'major',
  'table-html-broken': 'blocker',
  'table-pipe-mismatch': 'blocker',
  'table-row-mismatch': 'blocker',
  'terse-generic-rationale': 'major',
  'weak-rationale': 'major',
};

const SUBJECT_ALIASES = new Map([
  ['RLA', 'Reasoning Through Language Arts (RLA)'],
  [
    'Reasoning Through Language Arts (RLA)',
    'Reasoning Through Language Arts (RLA)',
  ],
  ['Science', 'Science'],
  ['Social Studies', 'Social Studies'],
  ['Math', 'Math'],
]);

function getBackendDir() {
  return path.resolve(__dirname, '../..');
}

function getRootDir() {
  return path.resolve(getBackendDir(), '..');
}

function canonicalizeSubject(subject) {
  return (
    SUBJECT_ALIASES.get(String(subject || '').trim()) ||
    String(subject || '').trim()
  );
}

function stripHtml(value) {
  if (typeof value !== 'string') return '';
  return value.replace(/<[^>]*>/g, ' ');
}

function normalizeText(value) {
  return stripHtml(value).replace(/\s+/g, ' ').trim();
}

function isPlaceholderText(value) {
  const text = normalizeText(value);
  if (!text) return true;
  if (text.length < 3) return true;
  // Note: a trailing "..." is a legitimate cloze / sentence-completion
  // pattern (e.g. "The Civil Rights Act of 1964 sought to...") and must NOT
  // be treated as placeholder text. Only structural placeholders below.
  return PLACEHOLDER_PATTERNS.some((pattern) => pattern.test(text));
}

function hasTableMarkup(value) {
  if (typeof value !== 'string') return false;
  return /<table[\s\S]*?>|\|.+\|/.test(value);
}

function referencesTableContext(text) {
  if (typeof text !== 'string') return false;
  const lower = text.toLowerCase();
  const ignorePhrases = [
    'kitchen table',
    'dining table',
    'coffee table',
    'tablecloth',
    'table manners',
    'table tennis',
    'table for two',
  ];
  if (ignorePhrases.some((phrase) => lower.includes(phrase))) {
    return false;
  }
  return /(table (below|above|shown|shows)|table\s*\d+|see (the )?table|in the table|data table|frequency table|reference table)/i.test(
    text
  );
}

function referencesPassageContext(text) {
  if (typeof text !== 'string') return false;
  // Skip when the prose references a constitutional/legal "Article I/II/..."
  // (e.g. "as listed in Article I, Section 8 of the Constitution"), since
  // that's a reference to a constitutional article, not a reading passage.
  const cleaned = text.replace(
    /\bArticle\s+(?:[IVX]+|\d+|One|Two|Three|Four|Five|Six|Seven)\b/g,
    ''
  );
  return /(according to|based on|from|in)\s+(the\s+)?(passage|excerpt|article|text)\b|\b(passage|excerpt|article|text)\s+(above|below|provided|states|suggests|indicates)\b/i.test(
    cleaned
  );
}

function referencesImageContext(text) {
  if (typeof text !== 'string') return false;
  // Only flag when the question explicitly directs the student to a visual
  // stimulus (image/graph/diagram shown to them), not when the prose merely
  // mentions a graph it is *describing* in detail.
  return (
    /\b(?:image|photo|diagram|graph|chart|map|cartoon|figure|illustration)\s+(?:above|below|shown|shows|provided|displayed|displays|depicts|depicted|to\s+the\s+(?:right|left))\b/i.test(
      text
    ) ||
    /\b(?:see|examine|observe|inspect|study|look\s+at|refer(?:ring)?\s+to|based\s+on|according\s+to|from|in|using)\s+(?:the\s+)?(?:image|photo|diagram|graph|chart|map|cartoon|figure|illustration)\b/i.test(
      text
    )
  );
}

function extractPipeTableRows(text) {
  if (typeof text !== 'string') return [];
  return (
    text
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line.includes('|') && line.split('|').length > 2)
      // Skip markdown header-divider rows like `| --- | --- |` or `|:--|--:|`
      .filter(
        (line) => !/^\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$/.test(line)
      )
  );
}

function countPipeColumns(line) {
  const trimmed = String(line || '').trim();
  if (!trimmed.includes('|')) return 0;
  let parts = trimmed.split('|');
  if (parts[0].trim() === '') parts = parts.slice(1);
  if (parts[parts.length - 1].trim() === '') parts = parts.slice(0, -1);
  return parts.length;
}

function getHtmlTableRows(html) {
  if (typeof html !== 'string') return [];
  const tables = html.match(/<table[\s\S]*?>[\s\S]*?<\/table>/gi) || [];
  return tables.map((table) => {
    const rows = [];
    const rowMatches = table.match(/<tr[\s\S]*?>[\s\S]*?<\/tr>/gi) || [];
    rowMatches.forEach((row) => {
      const cells = row.match(/<t[dh][\s\S]*?>/gi) || [];
      let count = 0;
      for (const cell of cells) {
        const m = /colspan\s*=\s*["']?(\d+)/i.exec(cell);
        count += m ? parseInt(m[1], 10) : 1;
      }
      rows.push(count);
    });
    return rows;
  });
}

function hasUnbalancedDelimiters(text, openToken, closeToken) {
  if (typeof text !== 'string') return false;
  const escapedOpen = openToken.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const escapedClose = closeToken.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`(${escapedOpen}|${escapedClose})`, 'g');
  let balance = 0;
  let match;
  while ((match = regex.exec(text))) {
    if (match[0] === openToken) balance += 1;
    if (match[0] === closeToken) balance -= 1;
    if (balance < 0) return true;
  }
  return balance !== 0;
}

function protectCurrency(source) {
  if (typeof source !== 'string') return source;
  return source.replace(/(?<!\\)\$\d[\d,]*(?:\.\d{1,2})?/g, (match) =>
    match.replace('$', '¤')
  );
}

function findUnescapedDollarCount(text) {
  if (typeof text !== 'string') return 0;
  let count = 0;
  for (let index = 0; index < text.length; index += 1) {
    if (text[index] !== '$' || text[index - 1] === '\\') {
      continue;
    }
    let lookAhead = index + 1;
    while (lookAhead < text.length && text[lookAhead] === ' ') {
      lookAhead += 1;
    }
    if (lookAhead < text.length && /\d/.test(text[lookAhead])) {
      continue;
    }
    if (text[index + 1] === '$') {
      index += 1;
      continue;
    }
    count += 1;
  }
  return count;
}

function hasUnbalancedBraces(latex) {
  if (typeof latex !== 'string') return false;
  let balance = 0;
  for (let index = 0; index < latex.length; index += 1) {
    const char = latex[index];
    if (char === '{' && latex[index - 1] !== '\\') balance += 1;
    if (char === '}' && latex[index - 1] !== '\\') balance -= 1;
    if (balance < 0) return true;
  }
  return balance !== 0;
}

function containsLatexCommandOutsideMath(text) {
  if (typeof text !== 'string') return false;
  return /(\\frac|\\sqrt|\\times|\\cdot|\\pi|\\theta|\\left|\\right|\\begin|\\end|\\sum|\\int|\\approx|\\neq|\\leq|\\geq)/.test(
    text
  );
}

function extractMathSegments(text) {
  if (typeof text !== 'string' || text.length === 0) {
    return [];
  }

  const segments = [];
  let buffer = '';

  const flushText = () => {
    if (!buffer) return;
    segments.push({ type: 'text', value: buffer });
    buffer = '';
  };

  const isEscapedAt = (source, index) => {
    let backslashes = 0;
    for (
      let position = index - 1;
      position >= 0 && source[position] === '\\';
      position -= 1
    ) {
      backslashes += 1;
    }
    return backslashes % 2 === 1;
  };

  let index = 0;
  while (index < text.length) {
    if (text[index] === '\\' && text[index + 1] === '$') {
      buffer += '$';
      index += 2;
      continue;
    }
    if (text[index] === '\\' && text[index + 1] === '(') {
      const close = text.indexOf('\\)', index + 2);
      if (close !== -1) {
        flushText();
        segments.push({
          type: 'math',
          raw: text.slice(index, close + 2),
          value: text.slice(index + 2, close),
        });
        index = close + 2;
        continue;
      }
    }
    if (text[index] === '\\' && text[index + 1] === '[') {
      const close = text.indexOf('\\]', index + 2);
      if (close !== -1) {
        flushText();
        segments.push({
          type: 'math',
          raw: text.slice(index, close + 2),
          value: text.slice(index + 2, close),
        });
        index = close + 2;
        continue;
      }
    }
    if (
      text[index] === '$' &&
      text[index + 1] === '$' &&
      !isEscapedAt(text, index)
    ) {
      const close = text.indexOf('$$', index + 2);
      if (close !== -1) {
        flushText();
        segments.push({
          type: 'math',
          raw: text.slice(index, close + 2),
          value: text.slice(index + 2, close),
        });
        index = close + 2;
        continue;
      }
    }
    if (
      text[index] === '$' &&
      !isEscapedAt(text, index) &&
      text[index + 1] !== '$'
    ) {
      let close = index + 1;
      while (close < text.length) {
        if (
          text[close] === '$' &&
          !isEscapedAt(text, close) &&
          text[close + 1] !== '$'
        ) {
          break;
        }
        close += 1;
      }
      if (close < text.length && text[close] === '$') {
        flushText();
        segments.push({
          type: 'math',
          raw: text.slice(index, close + 1),
          value: text.slice(index + 1, close),
        });
        index = close + 1;
        continue;
      }
    }
    buffer += text[index];
    index += 1;
  }

  flushText();
  return segments;
}

function walkImageDir(dirPath) {
  const results = [];
  if (!fs.existsSync(dirPath)) return results;
  for (const entry of fs.readdirSync(dirPath, { withFileTypes: true })) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkImageDir(fullPath));
    } else if (IMAGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      results.push(fullPath);
    }
  }
  return results;
}

function buildAssetSet(rootDir = getRootDir()) {
  const publicBase = path.join(rootDir, 'frontend', 'public');
  const imageRoot = path.join(publicBase, 'images');
  const files = walkImageDir(imageRoot);
  const assetPaths = new Set();
  for (const filePath of files) {
    assetPaths.add(
      '/' + path.relative(publicBase, filePath).replace(/\\/g, '/')
    );
  }
  return assetPaths;
}

function resolveAssetUrl(url, approvedAssets) {
  if (!url || typeof url !== 'string' || !url.trim()) {
    return { valid: true, resolvedPath: null, issue: null };
  }

  const trimmed = url.trim();
  if (/^https?:\/\//i.test(trimmed)) {
    return { valid: false, resolvedPath: null, issue: 'external-url' };
  }

  const normalized = trimmed.startsWith('//images/')
    ? trimmed.slice(1)
    : trimmed;
  if (approvedAssets.has(normalized)) {
    return { valid: true, resolvedPath: normalized, issue: null };
  }

  let decoded = normalized;
  try {
    decoded = decodeURIComponent(normalized);
  } catch {}

  if (approvedAssets.has(decoded)) {
    return { valid: true, resolvedPath: decoded, issue: null };
  }

  for (const asset of approvedAssets) {
    if (asset.toLowerCase() === decoded.toLowerCase()) {
      return { valid: true, resolvedPath: asset, issue: null };
    }
  }

  return { valid: false, resolvedPath: null, issue: 'missing-asset' };
}

function loadBackendPremadeCatalog() {
  const catalogPath = path.join(getBackendDir(), 'data', 'quizzes', 'index.js');
  delete require.cache[require.resolve(catalogPath)];
  const loaded = require(catalogPath);
  return loaded.ALL_QUIZZES || loaded;
}

function enumeratePremadeQuestions(catalog) {
  const entries = [];
  const sourcePath = 'backend/data/quizzes/index.js';

  for (const [subject, subjectData] of Object.entries(catalog || {})) {
    const canonicalSubject = canonicalizeSubject(subject);
    const categories = subjectData?.categories || {};
    for (const [categoryName, category] of Object.entries(categories)) {
      const topics = Array.isArray(category?.topics) ? category.topics : [];
      topics.forEach((topic) => {
        const baseContext = {
          sourcePath,
          subject: canonicalSubject,
          category: categoryName,
          topicId: topic?.id || null,
          topicTitle: topic?.title || topic?.id || null,
        };

        if (Array.isArray(topic?.questions)) {
          topic.questions.forEach((question, index) => {
            entries.push({
              question,
              context: {
                ...baseContext,
                quizId: topic?.id || null,
                quizTitle: topic?.title || topic?.id || null,
                questionNumber: question?.questionNumber || index + 1,
              },
            });
          });
        }

        if (Array.isArray(topic?.quizzes)) {
          topic.quizzes.forEach((quiz, quizIndex) => {
            const quizQuestions = Array.isArray(quiz?.questions)
              ? quiz.questions
              : [];
            quizQuestions.forEach((question, questionIndex) => {
              entries.push({
                question,
                context: {
                  ...baseContext,
                  quizId:
                    quiz?.quizId ||
                    quiz?.id ||
                    `${topic?.id || 'quiz'}-${quizIndex + 1}`,
                  quizTitle:
                    quiz?.title ||
                    quiz?.quizId ||
                    topic?.title ||
                    topic?.id ||
                    null,
                  questionNumber: question?.questionNumber || questionIndex + 1,
                },
              });
            });
          });
        }
      });
    }
  }

  return entries;
}

function enumerateQuestionFields(question) {
  const fields = [
    { name: 'question', value: getQuestionText(question) },
    { name: 'passage', value: getQuestionPassage(question) },
  ];

  const answerOptions = normalizeAnswerOptions(
    question?.answerOptions || question?.choices
  );
  answerOptions.forEach((option, index) => {
    fields.push({ name: `answer[${index}].text`, value: option.text });
    fields.push({
      name: `answer[${index}].rationale`,
      value: option.rationale,
    });
  });

  if (typeof question?.rationale === 'string' && question.rationale.trim()) {
    fields.push({ name: 'rationale', value: question.rationale });
  }
  if (typeof question?.correctAnswer === 'string') {
    fields.push({ name: 'correctAnswer', value: question.correctAnswer });
  }

  return fields;
}

function makeIssue(code, context = {}) {
  return {
    code,
    severity: ISSUE_SEVERITY[code] || 'major',
    ...context,
  };
}

function dedupeIssues(issues) {
  const seen = new Set();
  return issues.filter((issue) => {
    const key = [
      issue.code,
      issue.field || '',
      issue.detail || '',
      issue.patternKey || '',
    ].join('::');
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function auditMathField(field, subject) {
  const text = field.value;
  if (typeof text !== 'string' || !text.trim()) {
    return [];
  }

  const issues = [];
  const safeText = protectCurrency(text);
  const addMathIssue = (code, context = {}) => {
    issues.push(makeIssue(code, { field: field.name, ...context }));
  };

  if (
    hasUnbalancedDelimiters(safeText, '\\(', '\\)') ||
    hasUnbalancedDelimiters(safeText, '\\[', '\\]')
  ) {
    addMathIssue('math-latex-unbalanced');
  }

  const dollarCount = findUnescapedDollarCount(safeText);
  if (dollarCount % 2 !== 0) {
    addMathIssue('math-latex-dollar-unbalanced');
  }

  const segments = extractMathSegments(safeText);
  if (
    segments.some(
      (segment) => segment.type === 'math' && segment.raw.startsWith('$')
    )
  ) {
    addMathIssue('math-latex-dollar-delimiter');
  }

  const textOutsideMath = segments.length
    ? segments
        .filter((segment) => segment.type !== 'math')
        .map((segment) => segment.value)
        .join(' ')
    : safeText;

  if (containsLatexCommandOutsideMath(textOutsideMath)) {
    addMathIssue('math-command-outside-delimiters');
  }

  segments
    .filter((segment) => segment.type === 'math')
    .forEach((segment, index) => {
      if (hasUnbalancedBraces(segment.value)) {
        addMathIssue('math-latex-brace-unbalanced', {
          detail: `segment-${index + 1}`,
        });
      }
      if (
        /\b\d+\s*\/\s*\d+\b/.test(segment.value) &&
        !/\\frac/.test(segment.value) &&
        // Only flag when the segment is a *standalone* fraction (no equation
        // context). Arithmetic division like \(30 / 5 = 6\) reads better as
        // division than as a stacked \frac, so allow it.
        !/[=+\-]/.test(segment.value)
      ) {
        addMathIssue('math-plain-fraction-in-math', {
          detail: `segment-${index + 1}`,
        });
      }
    });

  if (subject === 'Math') {
    if (
      /\b\d+\s*\/\s*\d+\b/.test(textOutsideMath) ||
      /\b[A-Za-z]\s*\/\s*[A-Za-z]\b/.test(textOutsideMath)
    ) {
      addMathIssue('math-plain-fraction-outside-delimiters');
    }
    if (/\b(?:[A-Za-z0-9)\]}]+)\^\d+\b/.test(textOutsideMath)) {
      addMathIssue('math-plain-exponent-outside-delimiters');
    }
  }

  if (subject === 'Math' && issues.length > 0) {
    const sanitized = sanitizeMathText(text);
    if (typeof sanitized === 'string' && sanitized !== text) {
      issues.forEach((issue) => {
        issue.autofixable = true;
        if (sanitized.length <= 240) {
          issue.suggestedValue = sanitized;
        }
      });
    }
  }

  return issues;
}

function auditPremadeQuestion(entry, helpers) {
  const { question, context } = entry;
  const subjectQuestion = {
    ...question,
    subject: question?.subject || context.subject,
  };
  const questionText = getQuestionText(subjectQuestion);
  const passageText = getQuestionPassage(subjectQuestion);
  const answerOptions = normalizeAnswerOptions(
    subjectQuestion?.answerOptions || subjectQuestion?.choices
  );
  const rawImageRef = getQuestionImage(subjectQuestion);
  const imageRef = canonicalizeImageAssetPath(rawImageRef) || rawImageRef;
  const combinedText = [questionText, passageText].filter(Boolean).join('\n');
  const issues = [];
  const rawType = String(subjectQuestion?.type || '')
    .trim()
    .toLowerCase();
  const nonOptionType = new Set([
    'fillin',
    'fill-in',
    'fill_in',
    'numeric',
    'shortanswer',
    'short-answer',
    'essay',
    'extendedresponse',
    'extended-response',
    'dragdrop',
    'drag-drop',
    'hotspot',
  ]).has(rawType);

  if (isPlaceholderText(questionText)) {
    // Inline dropdown / cloze items use the passage (or
    // passageWithPlaceholders) as the prompt, so an empty `question` field
    // is expected; only flag if no cloze stimulus is present either.
    const itemType = String(subjectQuestion?.itemType || '').toLowerCase();
    const isClozeItem = itemType === 'inline_dropdown' || itemType === 'cloze';
    const hasClozeStimulus =
      typeof subjectQuestion?.passageWithPlaceholders === 'string' &&
      subjectQuestion.passageWithPlaceholders.trim().length > 0;
    if (!(isClozeItem && (hasClozeStimulus || passageText))) {
      issues.push(makeIssue('missing-prompt', { field: 'question' }));
    }
  }

  if (!nonOptionType) {
    answerOptions.forEach((option, index) => {
      if (!normalizeText(option.text)) {
        issues.push(
          makeIssue('missing-answer-text', {
            field: `answer[${index}].text`,
          })
        );
      }

      if (!normalizeText(option.rationale)) {
        issues.push(
          makeIssue('missing-answer-rationale', {
            field: `answer[${index}].rationale`,
          })
        );
      } else if (isPlaceholderText(option.rationale)) {
        issues.push(
          makeIssue('placeholder-rationale', {
            field: `answer[${index}].rationale`,
          })
        );
      }
    });
  }

  if (
    referencesPassageContext(questionText) &&
    isPlaceholderText(passageText)
  ) {
    issues.push(makeIssue('missing-stimulus-passage', { field: 'passage' }));
  }

  if (referencesImageContext(questionText) && !String(imageRef || '').trim()) {
    // graphSpec / graphInstructions render an interactive graph in place of an
    // image asset, so a missing imageUrl is not actually a missing stimulus.
    const hasGraphSpec =
      subjectQuestion?.graphSpec || subjectQuestion?.content?.graphSpec;
    // A passage that contains a real table (HTML or markdown pipe table) acts
    // as the chart/graph stimulus the question refers to.
    const passageHasTable =
      typeof passageText === 'string' && hasTableMarkup(passageText);
    // Items typed as `chart` (or with a non-trivial passage describing the
    // chart in text/HTML) supply the visual stimulus through the passage.
    const chartTyped =
      rawType === 'chart' &&
      typeof passageText === 'string' &&
      passageText.trim().length >= 40;
    if (!hasGraphSpec && !passageHasTable && !chartTyped) {
      issues.push(makeIssue('missing-stimulus-image', { field: 'image' }));
    }
  }

  if (
    (referencesTableContext(questionText) ||
      referencesTableContext(passageText)) &&
    !hasTableMarkup(combinedText)
  ) {
    issues.push(
      makeIssue('missing-stimulus-table', { field: 'question/passage' })
    );
  }

  if (
    typeof passageText === 'string' &&
    /<img\b/i.test(passageText) &&
    !/src\s*=\s*['"]/i.test(passageText)
  ) {
    issues.push(makeIssue('missing-stimulus-image', { field: 'passage' }));
  }

  if (typeof imageRef === 'string' && imageRef.trim()) {
    const assetResult = resolveAssetUrl(imageRef, helpers.approvedAssets);
    if (!assetResult.valid) {
      issues.push(
        makeIssue(
          assetResult.issue === 'missing-asset'
            ? 'image-asset-missing'
            : 'image-path-invalid',
          {
            field: 'image',
            detail: imageRef,
          }
        )
      );
    } else if (
      assetResult.resolvedPath &&
      !helpers.imageMetadataByPath.has(assetResult.resolvedPath)
    ) {
      issues.push(
        makeIssue('image-metadata-missing', {
          field: 'image',
          detail: assetResult.resolvedPath,
        })
      );
    }
  }

  if (typeof imageRef === 'string' && imageRef.trim()) {
    const normalized = String(imageRef).trim();
    if (
      /undefined|null/i.test(normalized) ||
      (!/(?:\.png|\.jpe?g|\.gif|\.svg|\.webp)(\?|#|$)/i.test(normalized) &&
        !/^data:image\//i.test(normalized) &&
        !helpers.approvedAssets.has(normalized))
    ) {
      issues.push(
        makeIssue('image-path-invalid', {
          field: 'image',
          detail: normalized,
        })
      );
    }
  }

  if (typeof combinedText === 'string' && combinedText.includes('<table')) {
    if (!combinedText.includes('</table>')) {
      issues.push(
        makeIssue('table-html-broken', { field: 'question/passage' })
      );
    }

    const rowsPerTable = getHtmlTableRows(combinedText);
    rowsPerTable.forEach((rows, index) => {
      if (rows.length < 2) return;
      const expected = rows[0];
      if (rows.some((count) => count !== expected)) {
        issues.push(
          makeIssue('table-row-mismatch', {
            field: 'question/passage',
            detail: `table-${index + 1}`,
          })
        );
      }
    });
  }

  const pipeRows = extractPipeTableRows(combinedText);
  if (pipeRows.length >= 2) {
    const baseColumnCount = countPipeColumns(pipeRows[0]);
    if (
      baseColumnCount > 1 &&
      pipeRows.some((row) => countPipeColumns(row) !== baseColumnCount)
    ) {
      issues.push(
        makeIssue('table-pipe-mismatch', { field: 'question/passage' })
      );
    }
  }

  const specificCodes = new Set(issues.map((issue) => issue.code));
  const suppressedCoreCodes = new Set();
  if (specificCodes.has('missing-prompt')) {
    suppressedCoreCodes.add('short-question-text');
  }
  if (specificCodes.has('missing-answer-rationale')) {
    suppressedCoreCodes.add('weak-rationale');
  }
  if (
    specificCodes.has('missing-stimulus-passage') ||
    specificCodes.has('missing-stimulus-image') ||
    specificCodes.has('missing-stimulus-table')
  ) {
    suppressedCoreCodes.add('missing-stimulus');
  }

  classifyCoreQuestionQualityIssues(subjectQuestion).forEach((code) => {
    if (!suppressedCoreCodes.has(code)) {
      issues.push(makeIssue(code));
    }
  });

  enumerateQuestionFields(subjectQuestion).forEach((field) => {
    issues.push(...auditMathField(field, context.subject));
  });

  return dedupeIssues(issues);
}

function buildReport(results) {
  const report = {
    generatedAt: new Date().toISOString(),
    sourceCatalog: 'backend/data/quizzes/index.js',
    totalQuestions: results.length,
    affectedQuestions: 0,
    cleanQuestions: 0,
    issueCount: 0,
    autofixableIssueCount: 0,
    severityCounts: {
      blocker: 0,
      major: 0,
      warning: 0,
    },
    issueCounts: {},
    bySubject: {},
    questions: [],
  };

  results.forEach((result) => {
    report.bySubject[result.subject] ||= {
      totalQuestions: 0,
      affectedQuestions: 0,
      issueCount: 0,
      issueCounts: {},
    };

    const subjectSummary = report.bySubject[result.subject];
    subjectSummary.totalQuestions += 1;

    if (result.issueCount > 0) {
      report.affectedQuestions += 1;
      subjectSummary.affectedQuestions += 1;
      report.questions.push(result);
    } else {
      report.cleanQuestions += 1;
    }

    result.issues.forEach((issue) => {
      report.issueCount += 1;
      subjectSummary.issueCount += 1;
      report.issueCounts[issue.code] =
        (report.issueCounts[issue.code] || 0) + 1;
      subjectSummary.issueCounts[issue.code] =
        (subjectSummary.issueCounts[issue.code] || 0) + 1;
      report.severityCounts[issue.severity] =
        (report.severityCounts[issue.severity] || 0) + 1;
      if (issue.autofixable) {
        report.autofixableIssueCount += 1;
      }
    });
  });

  return report;
}

function auditPremadeCatalog({ catalog, rootDir } = {}) {
  const workspaceRoot = rootDir || getRootDir();
  const premadeCatalog = catalog || loadBackendPremadeCatalog();
  const approvedAssets = buildAssetSet(workspaceRoot);
  const imageMetadataByPath = buildImageMetadataMap(
    loadMergedImageMetadata({ backendDir: getBackendDir() })
  );

  const entries = enumeratePremadeQuestions(premadeCatalog);
  const results = entries.map((entry) => {
    const issues = auditPremadeQuestion(entry, {
      approvedAssets,
      imageMetadataByPath,
    });
    return {
      sourcePath: entry.context.sourcePath,
      subject: entry.context.subject,
      category: entry.context.category,
      topicId: entry.context.topicId,
      topicTitle: entry.context.topicTitle,
      quizId: entry.context.quizId,
      quizTitle: entry.context.quizTitle,
      questionNumber: entry.context.questionNumber,
      excerpt: normalizeText(getQuestionText(entry.question)).slice(0, 180),
      issueCount: issues.length,
      issues,
    };
  });

  return buildReport(results);
}

module.exports = {
  auditPremadeCatalog,
  enumeratePremadeQuestions,
  loadBackendPremadeCatalog,
};
