// GED-flavored typing drill sentences. Mix of length and topic so practice
// also exposes students to vocabulary and phrasings common on the test.
export const TYPING_DRILLS = [
  'A balanced argument acknowledges credible evidence on both sides of an issue.',
  'Voter turnout among first-time citizens has increased steadily over the past decade.',
  'Scientists distinguish observations from inferences when designing controlled experiments.',
  'A persuasive essay relies on clear claims supported by relevant, specific examples.',
  'The Constitution divides power among the legislative, executive, and judicial branches.',
  'Many entrepreneurs reinvest early profits to expand inventory and hire additional staff.',
  'A well-placed transition signals how one idea connects to the next paragraph.',
  'Renewable energy sources include solar, wind, hydroelectric, and geothermal generation.',
  'Authors often reveal tone through word choice rather than direct statements of feeling.',
  'During photosynthesis, plants convert sunlight, water, and carbon dioxide into glucose.',
  'A reliable source provides verifiable evidence and a clear method for gathering data.',
  'The committee proposed a new ordinance after reviewing the neighborhood traffic study.',
  'Inflation reduces purchasing power, so wages must rise just to keep pace with prices.',
  'A topic sentence introduces the main idea that the rest of the paragraph develops.',
  'Counterarguments demonstrate fairness and strengthen the credibility of the writer.',
  'Effective summaries restate central ideas without repeating minor or unrelated details.',
  'The supreme court reviews lower court rulings only when significant legal questions arise.',
  'A scientific hypothesis must be specific enough that an experiment can disprove it.',
  'Compound sentences join two complete ideas using a comma and a coordinating conjunction.',
  'Skilled workers complete certifications more quickly when training combines theory and practice.',
  'Climate scientists track long-term trends rather than reacting to a single unusual season.',
  'A democracy depends on informed citizens who evaluate sources before drawing conclusions.',
  'Successful negotiations begin with each side stating its priorities clearly and respectfully.',
  'Historians compare primary documents to confirm whether contemporary accounts agree.',
  'Engineers prototype, test, and revise their designs before committing to a final version.',
  'Personal budgets allocate income across needs, savings, and a small portion for flexibility.',
  'Rhetorical questions guide the reader toward a conclusion the author has already implied.',
  'A topic loses focus when paragraphs introduce unrelated examples or shift purpose midway.',
  'Health agencies distribute clear, consistent messaging during emergencies to reduce confusion.',
  'A figurative comparison can clarify a complex idea by linking it to a familiar image.',
];
