DEFAULT_RATIONALE = "This option does not accurately reflect the concept described in the question."

def make_question(question, correct, incorrects, difficulty, explanation=None):
    answer_options = []
    correct_text, correct_rationale = correct
    answer_options.append({
        "text": correct_text,
        "isCorrect": True,
        "rationale": correct_rationale,
    })
    for item in incorrects:
        if isinstance(item, tuple):
            text, rationale = item
        else:
            text, rationale = item, None
        answer_options.append({
            "text": text,
            "isCorrect": False,
            "rationale": rationale or DEFAULT_RATIONALE,
        })
    q = {
        "type": "multipleChoice",
        "difficulty": difficulty,
        "question": question,
        "answerOptions": answer_options,
    }
    if explanation:
        q["explanation"] = explanation
    return q


def make_term_alignment_questions(items, prompt_template=None, rationale_template=None):
    """Create multiple-choice questions that match terms to definitions.

    items: list of dicts with keys term, definition, difficulty, optional explanation.
    prompt_template: optional str with {definition} placeholder.
    rationale_template: optional str with {term} and {definition} placeholders.
    """

    if prompt_template is None:
        prompt_template = "Which term best matches the following description: {definition}?"
    if rationale_template is None:
        rationale_template = "Correct. {term} is defined as {definition}."

    if len(items) < 4:
        raise ValueError("At least four items are required to build matching questions.")

    questions = []
    total = len(items)
    for idx, item in enumerate(items):
        term = item["term"]
        definition = item["definition"]
        difficulty = item.get("difficulty", "medium")
        explanation = item.get("explanation")
        correct = (
            term,
            rationale_template.format(term=term, definition=definition),
        )
        incorrect_terms = []
        for step in range(1, 4):
            candidate = items[(idx + step) % total]["term"]
            incorrect_terms.append(candidate)
        question_text = prompt_template.format(definition=definition)
        questions.append(
            make_question(
                question_text,
                correct,
                incorrect_terms,
                difficulty,
                explanation=explanation,
            )
        )
    return questions

QUESTION_BANK = {}

if __name__ == "__main__":
    raise SystemExit("This module defines QUESTION_BANK but is not meant to be executed directly.")
QUESTION_BANK.update({
    "ss_civics_constitutional_principles_set1": [
        make_question(
            "Which constitutional principle states that a government's authority comes from the people it governs?",
            ("Popular sovereignty", "Correct. Popular sovereignty means political power begins with the consent of the governed."),
            [
                ("Judicial review", "Judicial review allows courts to evaluate laws, not to grant power from the people."),
                ("Due process", "Due process protects individual rights during legal proceedings rather than creating governmental authority."),
                ("Nullification", "Nullification refers to a claimed state power to void federal laws, not the source of governmental power."),
            ],
            "easy",
        ),
        make_question(
            "What best describes federalism in the United States?",
            ("A division of power between national and state governments", "Correct. Federalism splits governing authority between national and state levels."),
            [
                ("A requirement that all power remain at the national level", "This describes a unitary system, not federalism."),
                ("An alliance of independent nations with no central authority", "That would be a confederation, not the U.S. federal system."),
                ("A system where power is held exclusively by the states", "States share power with the national government rather than holding it alone."),
            ],
            "easy",
        ),
        make_question(
            "Which action is an example of popular sovereignty in practice?",
            ("Voters approving a state constitutional amendment in a referendum", "Correct. Directly voting on constitutional changes demonstrates people governing themselves."),
            [
                ("The Supreme Court striking down an unconstitutional law", "This reflects judicial review, not direct rule by the people."),
                ("The president appointing a cabinet secretary", "Appointments are an executive power rather than an expression of popular sovereignty."),
                ("Congress overriding a presidential veto", "An override is a legislative check, not citizens exercising authority."),
            ],
            "medium",
        ),
        make_question(
            "Under federalism, which level of government typically oversees issuing driver's licenses?",
            ("State governments", "Correct. States retain reserved powers such as licensing drivers."),
            [
                ("The U.S. Supreme Court", "The judicial branch does not administer licensing."),
                ("County governments", "Counties may administer state rules, but authority originates from the state."),
                ("Congress", "Congress handles national matters, not routine state licensing."),
            ],
            "easy",
        ),
        make_question(
            "Why did the Framers include federalism in the Constitution?",
            ("To balance a stronger national government with continued state authority", "Correct. Federalism prevented both national weakness and domination over the states."),
            [
                ("To give the president power over state legislatures", "The Framers limited direct presidential control over states."),
                ("To replace all state governments with appointed officials", "The Framers retained elected state governments."),
                ("To allow states to set foreign policy independently", "Foreign affairs were delegated to the national government."),
            ],
            "medium",
        ),
        make_question(
            "Which amendment reserves powers not delegated to the United States for the states or the people?",
            ("Tenth Amendment", "Correct. The Tenth Amendment protects reserved powers under federalism."),
            [
                ("First Amendment", "The First Amendment protects individual liberties, not reserved powers."),
                ("Fourth Amendment", "The Fourth Amendment addresses searches and seizures."),
                ("Seventeenth Amendment", "The Seventeenth Amendment established direct election of senators."),
            ],
            "medium",
        ),
        make_question(
            "When Congress creates a law establishing nationwide environmental standards, which constitutional principle allows it to do so?",
            ("Enumerated powers granted to the national government", "Correct. Congress uses enumerated and implied powers to pass national legislation."),
            [
                ("Reserved powers of the states", "Reserved powers belong to the states, not Congress."),
                ("Judicial independence", "Judicial independence concerns the courts, not lawmaking authority."),
                ("Executive privilege", "Executive privilege relates to presidential confidentiality, not lawmaking."),
            ],
            "medium",
        ),
        make_question(
            "Shared powers held by both the national and state governments are known as what?",
            ("Concurrent powers", "Correct. Concurrent powers may be exercised by both levels, such as taxation."),
            [
                ("Delegated powers", "Delegated powers belong only to the national government."),
                ("Reserved powers", "Reserved powers belong exclusively to the states."),
                ("Expressed powers", "Expressed powers are specifically listed for the national government."),
            ],
            "medium",
        ),
        make_question(
            "Which Supreme Court case strengthened the idea of federal supremacy over the states?",
            ("McCulloch v. Maryland", "Correct. McCulloch affirmed federal supremacy and implied powers."),
            [
                ("Marbury v. Madison", "Marbury established judicial review, not federal supremacy over states."),
                ("Dred Scott v. Sandford", "Dred Scott dealt with citizenship and slavery, not federal supremacy."),
                ("Plessy v. Ferguson", "Plessy concerned segregation, not the balance of state and federal power."),
            ],
            "hard",
        ),
        make_question(
            "Which statement about federalism today is most accurate?",
            ("Federal and state governments frequently cooperate on policy areas like transportation and public health", "Correct. Modern federalism often features intergovernmental cooperation."),
            [
                ("Federalism no longer exists because the national government holds all power", "The Constitution still divides authority between national and state governments."),
                ("States cannot receive federal funding for shared programs", "States routinely receive federal funds for shared initiatives."),
                ("Only the president can decide when states may pass laws", "States continue to enact their own laws within constitutional boundaries."),
            ],
            "hard",
        ),
        make_question(
            "What does the Necessary and Proper Clause allow Congress to do within the federal system?",
            ("Create laws needed to carry out its enumerated powers", "Correct. The clause supports implied powers to implement expressed responsibilities."),
            [
                ("Overturn state constitutions without limitation", "The clause does not give Congress unlimited authority over states."),
                ("Appoint state governors directly", "Governors are chosen by state processes, not congressional appointment."),
                ("Amend the Constitution without state involvement", "Formal amendments require state ratification."),
            ],
            "hard",
        ),
        make_question(
            "A state law conflicts with a federal statute on the same subject. According to the Constitution, which law prevails?",
            ("The federal statute because of the Supremacy Clause", "Correct. The Supremacy Clause makes valid federal laws superior to conflicting state laws."),
            [
                ("The state law because states existed before the Constitution", "The Constitution gives priority to federal law when conflicts arise."),
                ("Neither law applies until the president makes a decision", "The Supremacy Clause resolves the conflict without presidential action."),
                ("Local governments choose which law to follow", "Local governments must comply with federal law when conflicts exist."),
            ],
            "medium",
        ),
        make_question(
            "What is one benefit of federalism for citizens?",
            ("It allows state governments to address regional needs while the national government handles nationwide concerns", "Correct. Federalism enables multiple levels of government to respond to different needs."),
            [
                ("It ensures every policy is identical in all fifty states", "Federalism allows states to experiment rather than requiring uniform policies."),
                ("It removes local governments from the decision-making process", "Federalism permits local participation through states and municipalities."),
                ("It prevents citizens from influencing national decisions", "Citizens can still influence national policy through elections and civic action."),
            ],
            "easy",
        ),
    ],
    "ss_civics_constitutional_principles_set2": [
        make_question(
            "Which branch of government is primarily responsible for making federal laws?",
            ("The legislative branch", "Correct. Congress writes and passes federal legislation."),
            ["The executive branch", "The judicial branch", "State governments"],
            "easy",
        ),
        make_question(
            "What power allows the president to reject a bill passed by Congress?",
            ("The veto", "Correct. The president may veto legislation as part of the separation of powers."),
            ["Judicial review", "Impeachment", "Filibuster"],
            "easy",
        ),
        make_question(
            "Which branch interprets the Constitution and reviews the legality of laws?",
            ("The judicial branch", "Correct. Federal courts interpret laws and the Constitution."),
            ["The legislative branch", "The executive branch", "The military"],
            "easy",
        ),
        make_question(
            "What is the purpose of separating government powers into different branches?",
            ("To prevent any single branch from becoming too powerful", "Correct. Separation of powers creates internal limits on government authority."),
            ["To reduce citizen participation", "To eliminate checks and balances", "To allow faster decision making"],
            "medium",
        ),
        make_question(
            "Which of the following is an example of Congress checking the executive branch?",
            ("The Senate rejecting a presidential treaty", "Correct. The Senate may refuse to ratify treaties, limiting executive power."),
            ["The Supreme Court declaring a law unconstitutional", "The president issuing an executive order", "The vice president presiding over the Senate"],
            "medium",
        ),
        make_question(
            "How can the judicial branch limit the power of Congress?",
            ("By declaring a law unconstitutional", "Correct. Judicial review allows courts to strike down laws that violate the Constitution."),
            ["By vetoing legislation", "By approving cabinet appointments", "By withholding federal funds"],
            "medium",
        ),
        make_question(
            "Which branch has the constitutional power to impeach federal officials?",
            ("The House of Representatives", "Correct. The House holds the power to impeach as part of legislative oversight."),
            ["The Supreme Court", "The Senate", "State legislatures"],
            "medium",
        ),
        make_question(
            "Why does the Constitution give the Senate the authority to confirm federal judges?",
            ("To provide a legislative check on judicial appointments", "Correct. Senate confirmation balances executive power to nominate judges."),
            ["To allow the judiciary to select its own members", "To ensure judges can be removed easily", "To keep the House of Representatives from voting"],
            "medium",
        ),
        make_question(
            "What check does the judicial branch have on the executive branch?",
            ("Courts can invalidate executive actions that violate the Constitution", "Correct. Courts may stop executive actions that exceed constitutional limits."),
            ["Judges can introduce legislation", "Judges can fire cabinet secretaries", "Judges control the military"],
            "hard",
        ),
        make_question(
            "Which statement best describes the relationship between the branches under separation of powers?",
            ("Each branch has distinct responsibilities but relies on the others to govern effectively", "Correct. Shared responsibilities require cooperation and oversight."),
            ["Each branch operates independently with no overlap", "Only the executive branch can overrule the others", "State governments coordinate the branches"],
            "hard",
        ),
        make_question(
            "What role does Congress play after a president negotiates a treaty?",
            ("The Senate must approve the treaty for it to take effect", "Correct. Senate ratification is a key legislative check on diplomacy."),
            ["The House submits the treaty to the Supreme Court", "The president alone decides ratification", "The Supreme Court votes to approve"],
            "medium",
        ),
        make_question(
            "How can Congress respond if the Supreme Court interprets a law in a way legislators disagree with?",
            ("Pass new legislation that clarifies congressional intent", "Correct. Congress can rewrite laws to address court interpretations."),
            ["Remove justices through executive order", "Refuse to fund the judiciary", "Suspend judicial elections"],
            "hard",
        ),
    ],
    "ss_civics_constitutional_principles_set3": [
        make_question(
            "What is one way the legislative branch can check the executive branch's appointments?",
            ("The Senate can refuse to confirm presidential nominees", "Correct. Senate confirmation prevents unilateral executive appointments."),
            ["The House can issue executive orders", "The Supreme Court can nominate cabinet members", "Governors can override nominations"],
            "medium",
        ),
        make_question(
            "How can the president check the lawmaking power of Congress?",
            ("By vetoing legislation", "Correct. A presidential veto forces Congress to reconsider or override."),
            ["By declaring laws unconstitutional", "By impeaching senators", "By dissolving Congress"],
            "easy",
        ),
        make_question(
            "Which action demonstrates the judicial branch checking the executive branch?",
            ("A federal court blocks an executive order that violates existing law", "Correct. Courts may halt executive actions that conflict with the Constitution or statutes."),
            ["The president issues a signing statement", "Congress holds confirmation hearings", "State courts adopt a local ordinance"],
            "hard",
        ),
        make_question(
            "What vote is needed in each chamber of Congress to override a presidential veto?",
            ("Two-thirds of both the House and the Senate", "Correct. A two-thirds vote in each chamber overrides a veto."),
            ["A simple majority in the House", "A unanimous vote in the Senate", "Approval by the Supreme Court"],
            "medium",
        ),
        make_question(
            "Which of the following is an example of checks and balances involving the judiciary?",
            ("The Senate conducts hearings before confirming a Supreme Court nominee", "Correct. Legislative oversight of nominations limits judicial appointments."),
            ["The president appoints a state judge", "Governors sign international treaties", "The House drafts state constitutions"],
            "medium",
        ),
        make_question(
            "Why does the Constitution give Congress control over the federal budget?",
            ("So the legislative branch can limit executive agencies through funding decisions", "Correct. Budget authority gives Congress influence over executive programs."),
            ["To allow judges to review spending bills", "To remove the need for taxation", "To grant states power over national spending"],
            "hard",
        ),
        make_question(
            "What check does Congress have on the judicial branch besides confirmation power?",
            ("Congress can propose constitutional amendments to respond to court decisions", "Correct. Amendments can overturn judicial rulings."),
            ["Congress can fire justices at will", "Congress can suspend court sessions indefinitely", "Congress can set state court jurisdictions"],
            "hard",
        ),
        make_question(
            "How does impeachment reflect checks and balances?",
            ("It allows the legislative branch to hold executive and judicial officials accountable", "Correct. Impeachment is a legislative tool to address misconduct in other branches."),
            ["It gives the Supreme Court power to remove senators", "It lets the president remove governors", "It allows states to rewrite federal laws"],
            "medium",
        ),
        make_question(
            "Which scenario illustrates a check on judicial power?",
            ("Congress sets the number of justices who serve on the Supreme Court", "Correct. The Constitution lets Congress determine the size of the Court."),
            ["The president decides the length of judicial terms", "State courts choose federal judges", "Governors certify federal court rulings"],
            "hard",
        ),
        make_question(
            "What can the president do if Congress passes a law the administration supports?",
            ("Sign the bill, allowing it to become law", "Correct. Presidential approval completes the legislative process."),
            ["Send the bill to the Supreme Court for review", "Order states to vote on the bill", "Rewrite the bill without Congress"],
            "easy",
        ),
        make_question(
            "How can citizens influence checks and balances directly?",
            ("By voting for representatives and senators who will hold other branches accountable", "Correct. Elections allow the public to shape how branches exercise their powers."),
            ["By vetoing bills through petition", "By appointing judges themselves", "By issuing executive orders"],
            "medium",
        ),
        make_question(
            "What happens if the Supreme Court rules a law unconstitutional?",
            ("The law is invalidated unless the Constitution is amended", "Correct. Judicial review can strike laws unless a constitutional change occurs."),
            ["The president may enforce it anyway", "The law automatically becomes a state statute", "Congress can enforce it without change"],
            "medium",
        ),
    ],
    "ss_civics_bill_of_rights_set1": [
        make_question(
            "Which freedom is protected by the First Amendment?",
            ("Freedom of speech", "Correct. The First Amendment shields speech from government interference."),
            ["Protection against unreasonable searches", "The right to a speedy trial", "Protection from excessive bail"],
            "easy",
        ),
        make_question(
            "What does the Second Amendment guarantee?",
            ("The right to keep and bear arms", "Correct. The Second Amendment protects an individual right to possess firearms."),
            ["Freedom from quartering soldiers", "Protection against self-incrimination", "The right to due process"],
            "easy",
        ),
        make_question(
            "Which amendment prevents the government from forcing citizens to house soldiers in peacetime?",
            ("Third Amendment", "Correct. The Third Amendment prohibits quartering soldiers without consent."),
            ["Fourth Amendment", "Fifth Amendment", "Eighth Amendment"],
            "medium",
        ),
        make_question(
            "What protection does the Fourth Amendment provide?",
            ("It guards against unreasonable searches and seizures", "Correct. Warrants must be based on probable cause."),
            ["It guarantees a jury trial in civil cases", "It limits cruel and unusual punishments", "It requires the government to pay fair compensation for property"],
            "medium",
        ),
        make_question(
            "According to the Fifth Amendment, which right is guaranteed to people accused of crimes?",
            ("Protection against double jeopardy", "Correct. Individuals cannot be tried twice for the same offense."),
            ["Right to vote", "Right to bear arms", "Right to a public defender in civil cases"],
            "medium",
        ),
        make_question(
            "Which amendment ensures the government must provide just compensation when taking private property for public use?",
            ("Fifth Amendment", "Correct. The Takings Clause requires fair payment for eminent domain."),
            ["Third Amendment", "Fourth Amendment", "Sixth Amendment"],
            "medium",
        ),
        make_question(
            "What does the phrase 'due process of law' mean in the context of the Bill of Rights?",
            ("The government must follow fair procedures before taking away life, liberty, or property", "Correct. Due process protects individuals from arbitrary actions."),
            ["Citizens must always represent themselves in court", "Only Congress can pass laws", "All trials must be held in secret"],
            "hard",
        ),
        make_question(
            "Which right is protected by the First Amendment in addition to speech and press?",
            ("Freedom of religion", "Correct. The First Amendment includes free exercise and establishment clauses."),
            ["Right to a jury in civil cases", "Protection from excessive fines", "Right to vote"],
            "easy",
        ),
        make_question(
            "What protection does the Fifth Amendment offer regarding self-incrimination?",
            ("A person cannot be forced to testify against themselves", "Correct. Individuals may remain silent to avoid self-incrimination."),
            ["All confessions must be written", "Only witnesses can refuse testimony", "Only applies in civil cases"],
            "medium",
        ),
        make_question(
            "If police search a home without a warrant or probable cause, which amendment might be violated?",
            ("The Fourth Amendment", "Correct. Searches generally require probable cause and a warrant."),
            ["The Third Amendment", "The Fifth Amendment", "The Seventh Amendment"],
            "medium",
        ),
        make_question(
            "Why were the first five amendments included in the Bill of Rights?",
            ("To protect individual liberties from potential government overreach", "Correct. The early amendments assure core civil freedoms."),
            ["To create new branches of government", "To outline state borders", "To expand federal taxation powers"],
            "medium",
        ),
        make_question(
            "Which amendment ensures citizens can peacefully assemble and petition the government?",
            ("First Amendment", "Correct. It guarantees assembly and petition rights."),
            ["Second Amendment", "Fourth Amendment", "Fifth Amendment"],
            "easy",
        ),
    ],
    "ss_civics_bill_of_rights_set2": make_term_alignment_questions([
        {"term": "Speedy trial", "definition": "The government must bring criminal defendants to trial without unnecessary delay under the Sixth Amendment.", "difficulty": "medium"},
        {"term": "Public trial", "definition": "Criminal proceedings should be open to the public unless a compelling reason requires closure.", "difficulty": "medium"},
        {"term": "Impartial jury", "definition": "Jurors must be unbiased members of the community where the alleged crime occurred.", "difficulty": "medium"},
        {"term": "Notice of charges", "definition": "Defendants have the right to know the nature and cause of the accusations against them.", "difficulty": "easy"},
        {"term": "Confronting witnesses", "definition": "The accused can question prosecution witnesses in court.", "difficulty": "medium"},
        {"term": "Compulsory process", "definition": "Defendants can require witnesses to appear in their favor.", "difficulty": "hard"},
        {"term": "Right to counsel", "definition": "Individuals charged with crimes are entitled to the assistance of an attorney.", "difficulty": "easy"},
        {"term": "Civil jury trial", "definition": "In most federal civil cases exceeding twenty dollars, litigants may request a jury.", "difficulty": "medium"},
        {"term": "Excessive bail", "definition": "Bail amounts cannot be set so high that they become punitive rather than ensuring appearance at trial.", "difficulty": "medium"},
        {"term": "Cruel and unusual punishment", "definition": "Punishments must be proportionate and not deliberately degrading.", "difficulty": "hard"},
        {"term": "Unenumerated rights", "definition": "Rights not specifically listed in the Constitution are still protected for the people.", "difficulty": "hard"},
        {"term": "Reserved powers", "definition": "Authority not delegated to the United States is kept by the states or the people.", "difficulty": "medium"},
    ]),
    "ss_civics_bill_of_rights_set3": make_term_alignment_questions([
        {"term": "Freedom of assembly", "definition": "Citizens may gather in groups for peaceful purposes without government interference.", "difficulty": "medium"},
        {"term": "Free exercise of religion", "definition": "Individuals can practice their faith without unreasonable government restriction.", "difficulty": "medium"},
        {"term": "Protection against quartering", "definition": "Households cannot be forced to house soldiers in peacetime.", "difficulty": "easy"},
        {"term": "Probable cause warrant", "definition": "Officials must show a justified reason before searching homes or seizing property.", "difficulty": "medium"},
        {"term": "Grand jury indictment", "definition": "Serious federal crimes require formal charges from citizens before trial.", "difficulty": "hard"},
        {"term": "Self-incrimination safeguard", "definition": "Accused people cannot be compelled to provide testimony against themselves.", "difficulty": "medium"},
        {"term": "Double jeopardy protection", "definition": "No person may be tried twice for the same offense after an acquittal.", "difficulty": "medium"},
        {"term": "Takings Clause", "definition": "Government must provide fair payment when seizing private property for public use.", "difficulty": "medium"},
        {"term": "Right to counsel", "definition": "The government must allow accused individuals access to legal representation.", "difficulty": "easy"},
        {"term": "Excessive fines ban", "definition": "Penalties must be proportional and cannot be used merely to punish financially.", "difficulty": "hard"},
        {"term": "Ninth Amendment principle", "definition": "Even if a liberty is not listed, it can still belong to the people.", "difficulty": "hard"},
        {"term": "Tenth Amendment guarantee", "definition": "Powers not given to the national government remain with states or citizens.", "difficulty": "medium"},
    ]),
    "ss_civics_gov_structure_set1": make_term_alignment_questions([
        {"term": "Article I", "definition": "Part of the Constitution that establishes the legislative branch and its powers.", "difficulty": "medium"},
        {"term": "Article II", "definition": "Section of the Constitution outlining the executive branch and presidential responsibilities.", "difficulty": "medium"},
        {"term": "Article III", "definition": "Constitutional article that creates the federal judiciary and defines its jurisdiction.", "difficulty": "medium"},
        {"term": "Bicameral legislature", "definition": "A lawmaking body composed of two chambers, the House of Representatives and the Senate.", "difficulty": "easy"},
        {"term": "Commander in chief", "definition": "Role of the president as head of the United States armed forces.", "difficulty": "easy"},
        {"term": "Cabinet", "definition": "Group of executive department leaders who advise the president on policy matters.", "difficulty": "medium"},
        {"term": "Judicial review", "definition": "Power of the courts to declare laws and executive actions unconstitutional.", "difficulty": "hard"},
        {"term": "State of the Union", "definition": "Annual message in which the president reports on national conditions to Congress.", "difficulty": "easy"},
        {"term": "Vice president", "definition": "Executive official who presides over the Senate and succeeds the president if needed.", "difficulty": "medium"},
        {"term": "Independent agencies", "definition": "Federal bodies outside cabinet departments that carry out specific tasks such as regulation.", "difficulty": "hard"},
        {"term": "Federal court system", "definition": "Hierarchy of district, appellate, and supreme courts handling cases under national law.", "difficulty": "medium"},
        {"term": "Checks and balances", "definition": "Structural principle ensuring each branch can limit the actions of the others.", "difficulty": "medium"},
    ]),
    "ss_civics_gov_structure_set2": make_term_alignment_questions([
        {"term": "House of Representatives", "definition": "Chamber where seats are apportioned by state population and members serve two-year terms.", "difficulty": "easy"},
        {"term": "Senate", "definition": "Chamber where each state has two members serving six-year terms.", "difficulty": "easy"},
        {"term": "Speaker of the House", "definition": "Presiding officer of the House who guides legislation and majority strategy.", "difficulty": "medium"},
        {"term": "President pro tempore", "definition": "Senator who presides when the vice president is absent, typically the majority party's senior member.", "difficulty": "hard"},
        {"term": "Standing committee", "definition": "Permanent congressional body that handles legislation on specific subjects.", "difficulty": "medium"},
        {"term": "Conference committee", "definition": "Temporary panel that reconciles House and Senate versions of a bill.", "difficulty": "medium"},
        {"term": "Executive departments", "definition": "Major administrative units such as the Departments of State or Education.", "difficulty": "medium"},
        {"term": "Regulatory commission", "definition": "Independent agency that enforces rules for specific economic or public sectors.", "difficulty": "hard"},
        {"term": "Judicial precedent", "definition": "Prior court decision that guides future rulings on similar legal questions.", "difficulty": "hard"},
        {"term": "Original jurisdiction", "definition": "Authority of a court to hear a case first rather than on appeal.", "difficulty": "medium"},
        {"term": "Appellate jurisdiction", "definition": "Authority of a court to review decisions made by lower courts.", "difficulty": "medium"},
        {"term": "Administrative law", "definition": "Rules issued by executive agencies to implement statutes passed by Congress.", "difficulty": "hard"},
    ]),
    "ss_civics_gov_structure_set3": make_term_alignment_questions([
        {"term": "Supremacy Clause", "definition": "Provision stating that the Constitution and federal laws take priority over conflicting state laws.", "difficulty": "hard"},
        {"term": "Necessary and Proper Clause", "definition": "Language giving Congress flexibility to pass laws needed to execute its enumerated powers.", "difficulty": "hard"},
        {"term": "Enumerated powers", "definition": "Specific authorities granted to Congress in Article I, Section 8.", "difficulty": "medium"},
        {"term": "Reserved powers", "definition": "Authorities retained by state governments under the Tenth Amendment.", "difficulty": "medium"},
        {"term": "Concurrent powers", "definition": "Responsibilities shared by national and state governments, such as taxation.", "difficulty": "medium"},
        {"term": "Full Faith and Credit Clause", "definition": "Requirement that states respect the public acts and judicial decisions of other states.", "difficulty": "hard"},
        {"term": "Extradition", "definition": "Process through which a state returns a suspected or convicted criminal to the state where the crime occurred.", "difficulty": "medium"},
        {"term": "Block grant", "definition": "Federal funding provided to states with broad spending guidelines.", "difficulty": "medium"},
        {"term": "Categorical grant", "definition": "Federal money designated for specific programs with strict requirements.", "difficulty": "medium"},
        {"term": "Dual federalism", "definition": "Concept of national and state governments operating in clearly defined policy areas.", "difficulty": "hard"},
        {"term": "Cooperative federalism", "definition": "Model in which levels of government work together to solve policy problems.", "difficulty": "hard"},
        {"term": "Devolution", "definition": "Shifting responsibilities from the national government back to state or local governments.", "difficulty": "hard"},
    ]),
    "ss_civics_elections_set1": make_term_alignment_questions([
        {"term": "Political party platform", "definition": "Formal statement of principles and policy goals adopted by a party at its convention.", "difficulty": "medium"},
        {"term": "Party realignment", "definition": "Significant shift in voter loyalty from one party to another that lasts for decades.", "difficulty": "hard"},
        {"term": "Two-party system", "definition": "Structure in which two major parties dominate national elections.", "difficulty": "easy"},
        {"term": "Third parties", "definition": "Smaller political groups that introduce new ideas or represent specific interests.", "difficulty": "medium"},
        {"term": "Party caucus", "definition": "Meeting of party members to coordinate strategy or select candidates.", "difficulty": "medium"},
        {"term": "National committee", "definition": "Organization that manages party affairs between conventions and supports candidates.", "difficulty": "medium"},
        {"term": "Grassroots organizing", "definition": "Building political support through local activism and volunteer efforts.", "difficulty": "medium"},
        {"term": "Party identification", "definition": "An individual's long-term psychological attachment to a political party.", "difficulty": "medium"},
        {"term": "Coalition", "definition": "Group of different voters or organizations joining forces to support a party.", "difficulty": "easy"},
        {"term": "Patronage", "definition": "Practice of rewarding loyal supporters with government jobs or favors.", "difficulty": "hard"},
        {"term": "Issue advocacy", "definition": "Political communication that promotes a viewpoint on public policy without directly urging a specific vote.", "difficulty": "hard"},
        {"term": "Party polarization", "definition": "Growing ideological distance between the major political parties.", "difficulty": "hard"},
    ]),
    "ss_civics_elections_set2": make_term_alignment_questions([
        {"term": "Primary election", "definition": "Vote in which party members choose nominees for the general election.", "difficulty": "easy"},
        {"term": "Caucus", "definition": "Local meeting where party members discuss and select candidates or delegates.", "difficulty": "medium"},
        {"term": "General election", "definition": "Nationwide vote held in November to choose public officials.", "difficulty": "easy"},
        {"term": "Electoral College", "definition": "Body of electors chosen by states to formally select the president and vice president.", "difficulty": "medium"},
        {"term": "Popular vote", "definition": "Total number of individual ballots cast by voters across the country.", "difficulty": "easy"},
        {"term": "Winner-take-all", "definition": "System in which the candidate receiving the most votes wins all of a state's electors.", "difficulty": "medium"},
        {"term": "Swing state", "definition": "State where support for major parties is closely divided and outcomes are uncertain.", "difficulty": "medium"},
        {"term": "Incumbent", "definition": "Current officeholder seeking reelection.", "difficulty": "easy"},
        {"term": "Voter registration", "definition": "Process citizens must complete before casting ballots in many states.", "difficulty": "medium"},
        {"term": "Absentee ballot", "definition": "Voting method allowing citizens to cast ballots by mail before Election Day.", "difficulty": "medium"},
        {"term": "Campaign finance", "definition": "Fundraising and spending activities supporting political candidates and parties.", "difficulty": "hard"},
        {"term": "Turnout", "definition": "Percentage of eligible voters who actually participate in an election.", "difficulty": "medium"},
    ]),
    "ss_civics_elections_set3": make_term_alignment_questions([
        {"term": "Voting Rights Act of 1965", "definition": "Federal law that outlawed literacy tests and strengthened enforcement of voting rights.", "difficulty": "hard"},
        {"term": "Motor Voter Act", "definition": "Legislation allowing citizens to register to vote when applying for a driver's license.", "difficulty": "medium"},
        {"term": "Gerrymandering", "definition": "Drawing electoral district boundaries to benefit a particular party or group.", "difficulty": "hard"},
        {"term": "Campaign debate", "definition": "Public forum where candidates present and defend their positions before voters.", "difficulty": "medium"},
        {"term": "Political action committee", "definition": "Organization that raises and spends money to influence elections.", "difficulty": "medium"},
        {"term": "Super PAC", "definition": "Independent group that can raise unlimited funds to advocate for or against candidates without coordinating.", "difficulty": "hard"},
        {"term": "Straight-ticket voting", "definition": "Casting ballots for all candidates from the same political party.", "difficulty": "medium"},
        {"term": "Split-ticket voting", "definition": "Selecting candidates from different parties for various offices on the same ballot.", "difficulty": "medium"},
        {"term": "Voter turnout", "definition": "Share of eligible citizens who participate in an election.", "difficulty": "easy"},
        {"term": "Campaign media strategy", "definition": "Plan to use television, radio, digital platforms, and print to communicate with voters.", "difficulty": "medium"},
        {"term": "Get-out-the-vote", "definition": "Effort by campaigns to mobilize supporters on or before Election Day.", "difficulty": "medium"},
        {"term": "Poll watcher", "definition": "Volunteer who monitors voting locations to ensure procedures are followed.", "difficulty": "medium"},
    ]),
    "ss_civics_supreme_court_set1": make_term_alignment_questions([
        {"term": "Marbury v. Madison", "definition": "1803 case establishing the power of judicial review for the Supreme Court.", "difficulty": "hard"},
        {"term": "McCulloch v. Maryland", "definition": "1819 decision affirming federal supremacy and the implied powers doctrine.", "difficulty": "hard"},
        {"term": "Gibbons v. Ogden", "definition": "1824 ruling confirming federal authority to regulate interstate commerce.", "difficulty": "hard"},
        {"term": "Dred Scott v. Sandford", "definition": "1857 case declaring that enslaved people were not citizens and striking down the Missouri Compromise.", "difficulty": "hard"},
        {"term": "Plessy v. Ferguson", "definition": "1896 decision upholding 'separate but equal' racial segregation laws.", "difficulty": "medium"},
        {"term": "Brown v. Board of Education", "definition": "1954 ruling that racial segregation in public schools is unconstitutional.", "difficulty": "medium"},
        {"term": "Gideon v. Wainwright", "definition": "1963 case guaranteeing the right to counsel for indigent defendants in felony trials.", "difficulty": "medium"},
        {"term": "Miranda v. Arizona", "definition": "1966 decision requiring police to inform suspects of their rights before interrogation.", "difficulty": "medium"},
        {"term": "Tinker v. Des Moines", "definition": "1969 case protecting students' First Amendment rights to symbolic speech in schools.", "difficulty": "medium"},
        {"term": "New Jersey v. T.L.O.", "definition": "1985 decision permitting school officials to conduct reasonable searches of students without a warrant.", "difficulty": "hard"},
        {"term": "United States v. Nixon", "definition": "1974 ruling limiting executive privilege and compelling release of Watergate tapes.", "difficulty": "hard"},
        {"term": "Roe v. Wade", "definition": "1973 case recognizing a constitutional right to privacy encompassing abortion decisions.", "difficulty": "hard"},
    ]),
    "ss_civics_supreme_court_set2": make_term_alignment_questions([
        {"term": "Engel v. Vitale", "definition": "1962 case striking down state-sponsored prayer in public schools.", "difficulty": "medium"},
        {"term": "Mapp v. Ohio", "definition": "1961 decision applying the exclusionary rule to evidence obtained through illegal searches.", "difficulty": "hard"},
        {"term": "Schenck v. United States", "definition": "1919 ruling establishing the 'clear and present danger' test for restricting speech.", "difficulty": "hard"},
        {"term": "Korematsu v. United States", "definition": "1944 case upholding Japanese American internment during World War II.", "difficulty": "hard"},
        {"term": "Texas v. Johnson", "definition": "1989 decision protecting flag burning as symbolic speech under the First Amendment.", "difficulty": "medium"},
        {"term": "Loving v. Virginia", "definition": "1967 case striking down state bans on interracial marriage.", "difficulty": "medium"},
        {"term": "Regents of the University of California v. Bakke", "definition": "1978 decision addressing affirmative action and prohibiting racial quotas.", "difficulty": "hard"},
        {"term": "Obergefell v. Hodges", "definition": "2015 ruling recognizing same-sex marriage nationwide under the Fourteenth Amendment.", "difficulty": "medium"},
        {"term": "Citizens United v. FEC", "definition": "2010 case expanding independent political spending rights for corporations and unions.", "difficulty": "hard"},
        {"term": "Shelby County v. Holder", "definition": "2013 decision striking down part of the Voting Rights Act's coverage formula.", "difficulty": "hard"},
        {"term": "Baker v. Carr", "definition": "1962 ruling allowing federal courts to hear legislative redistricting cases.", "difficulty": "hard"},
        {"term": "New York Times v. United States", "definition": "1971 case protecting freedom of the press in the Pentagon Papers dispute.", "difficulty": "medium"},
    ]),
    "ss_civics_supreme_court_set3": make_term_alignment_questions([
        {"term": "Hazelwood v. Kuhlmeier", "definition": "1988 decision allowing school administrators to edit student newspapers for legitimate educational concerns.", "difficulty": "medium"},
        {"term": "Bethel v. Fraser", "definition": "1986 case permitting schools to discipline students for lewd speech at assemblies.", "difficulty": "medium"},
        {"term": "Wisconsin v. Yoder", "definition": "1972 ruling allowing Amish parents to withdraw children from public school after eighth grade for religious reasons.", "difficulty": "medium"},
        {"term": "Griswold v. Connecticut", "definition": "1965 decision recognizing marital privacy in contraceptive use.", "difficulty": "hard"},
        {"term": "McDonald v. Chicago", "definition": "2010 case applying the Second Amendment right to bear arms to the states.", "difficulty": "hard"},
        {"term": "United States v. Lopez", "definition": "1995 ruling limiting Congress's commerce power over gun-free school zones.", "difficulty": "hard"},
        {"term": "Riley v. California", "definition": "2014 decision requiring police to obtain warrants before searching cell phones during arrests.", "difficulty": "hard"},
        {"term": "Terry v. Ohio", "definition": "1968 case allowing limited police stops and frisks based on reasonable suspicion.", "difficulty": "hard"},
        {"term": "Boumediene v. Bush", "definition": "2008 ruling granting Guantanamo detainees the right to challenge detention in federal court.", "difficulty": "hard"},
        {"term": "Roper v. Simmons", "definition": "2005 decision prohibiting the death penalty for crimes committed by minors.", "difficulty": "medium"},
        {"term": "Miller v. Alabama", "definition": "2012 case barring mandatory life without parole sentences for juveniles.", "difficulty": "medium"},
        {"term": "Masterpiece Cakeshop v. Colorado Civil Rights Commission", "definition": "2018 ruling that a state violated a baker's religious rights while enforcing anti-discrimination laws.", "difficulty": "hard"},
    ]),
    "ss_us_hist_colonial_period_set1": make_term_alignment_questions([
        {"term": "Jamestown", "definition": "1607 settlement that became the first permanent English colony in North America.", "difficulty": "easy"},
        {"term": "Powhatan Confederacy", "definition": "Native American alliance in Virginia that initially traded with English settlers.", "difficulty": "medium"},
        {"term": "House of Burgesses", "definition": "1619 representative assembly that allowed colonists to make local laws in Virginia.", "difficulty": "medium"},
        {"term": "Indentured servant", "definition": "Laborer who worked for a set time in exchange for passage to the colonies.", "difficulty": "easy"},
        {"term": "Mayflower Compact", "definition": "1620 agreement creating self-government for Pilgrims in Plymouth Colony.", "difficulty": "medium"},
        {"term": "Puritans", "definition": "Religious group seeking to purify the Church of England who settled Massachusetts Bay.", "difficulty": "medium"},
        {"term": "Town meeting", "definition": "Form of direct democracy in New England where male property owners voted on local issues.", "difficulty": "medium"},
        {"term": "Mercantilism", "definition": "Economic theory that colonies exist to enrich the mother country through controlled trade.", "difficulty": "hard"},
        {"term": "Triangular trade", "definition": "Exchange network connecting Europe, Africa, and the Americas with goods and enslaved people.", "difficulty": "hard"},
        {"term": "Middle Passage", "definition": "Brutal transatlantic journey that transported enslaved Africans to the Americas.", "difficulty": "hard"},
        {"term": "Salem witch trials", "definition": "1692 series of prosecutions in Massachusetts fueled by fear of witchcraft.", "difficulty": "medium"},
        {"term": "Navigation Acts", "definition": "British laws requiring colonial trade to pass through English ships and ports.", "difficulty": "hard"},
    ]),
    "ss_us_hist_colonial_period_set2": make_term_alignment_questions([
        {"term": "William Penn", "definition": "Quaker founder of Pennsylvania who promoted religious tolerance and representative government.", "difficulty": "medium"},
        {"term": "Pennsylvania Frame of Government", "definition": "1682 charter granting religious freedom and elected assemblies in the colony.", "difficulty": "hard"},
        {"term": "Middle Colonies", "definition": "Region including New York and Pennsylvania noted for diverse populations and commerce.", "difficulty": "easy"},
        {"term": "New Amsterdam", "definition": "Dutch settlement later renamed New York after English conquest in 1664.", "difficulty": "medium"},
        {"term": "Proprietary colony", "definition": "Territory granted by the king to individuals who governed it as owners.", "difficulty": "medium"},
        {"term": "Bacon's Rebellion", "definition": "1676 uprising of Virginia settlers protesting frontier defense and colonial leadership.", "difficulty": "hard"},
        {"term": "Great Awakening", "definition": "Religious revival movement of the 1730s and 1740s emphasizing personal faith.", "difficulty": "medium"},
        {"term": "Jonathan Edwards", "definition": "Influential preacher whose sermon 'Sinners in the Hands of an Angry God' fueled revivalism.", "difficulty": "hard"},
        {"term": "Salutary neglect", "definition": "Period when Britain loosely enforced colonial trade laws, fostering self-government.", "difficulty": "hard"},
        {"term": "Cash crops", "definition": "Agricultural products grown for profit, such as tobacco, rice, or indigo.", "difficulty": "easy"},
        {"term": "Slave codes", "definition": "Colonial laws restricting the freedom and movement of enslaved people.", "difficulty": "medium"},
        {"term": "Backcountry", "definition": "Frontier region along the Appalachian Mountains settled by Scots-Irish and German immigrants.", "difficulty": "medium"},
    ]),
    "ss_us_hist_colonial_period_set3": make_term_alignment_questions([
        {"term": "French and Indian War", "definition": "Conflict from 1754 to 1763 in which Britain and its colonies fought France and Native allies.", "difficulty": "medium"},
        {"term": "Albany Plan of Union", "definition": "Benjamin Franklin's 1754 proposal to coordinate colonial defense and governance.", "difficulty": "hard"},
        {"term": "Treaty of Paris 1763", "definition": "Agreement ending the French and Indian War and giving Britain control of Canada.", "difficulty": "medium"},
        {"term": "Proclamation of 1763", "definition": "Royal order forbidding colonists from settling west of the Appalachian Mountains.", "difficulty": "medium"},
        {"term": "Pontiac's Rebellion", "definition": "1763 Native American uprising resisting British rule in the Great Lakes region.", "difficulty": "hard"},
        {"term": "Enlightenment", "definition": "Intellectual movement stressing reason, natural rights, and social contracts.", "difficulty": "medium"},
        {"term": "John Locke", "definition": "Philosopher whose ideas about natural rights influenced colonial leaders.", "difficulty": "medium"},
        {"term": "Social contract", "definition": "Theory that governments derive authority from the consent of the governed.", "difficulty": "medium"},
        {"term": "Salutary neglect", "definition": "British policy of loosely enforcing colonial regulations before the 1760s.", "difficulty": "hard"},
        {"term": "Colonial assemblies", "definition": "Locally elected legislatures that managed taxation and laws within colonies.", "difficulty": "medium"},
        {"term": "Quartering", "definition": "Requirement for colonists to provide housing for British soldiers.", "difficulty": "medium"},
        {"term": "Smuggling", "definition": "Illegal trading to avoid British restrictions or taxes.", "difficulty": "medium"},
    ]),
    "ss_us_hist_american_revolution_set1": make_term_alignment_questions([
        {"term": "Stamp Act", "definition": "1765 law taxing printed materials in the colonies, sparking widespread protest.", "difficulty": "medium"},
        {"term": "Sons of Liberty", "definition": "Colonial organization that resisted British policies through boycotts and demonstrations.", "difficulty": "medium"},
        {"term": "Boston Massacre", "definition": "1770 confrontation in which British soldiers killed five colonial protesters.", "difficulty": "medium"},
        {"term": "Tea Act", "definition": "1773 law granting the British East India Company a monopoly, prompting colonial resentment.", "difficulty": "medium"},
        {"term": "Boston Tea Party", "definition": "December 1773 protest where colonists dumped British tea into the harbor.", "difficulty": "medium"},
        {"term": "Intolerable Acts", "definition": "1774 punitive laws closing Boston Harbor and altering Massachusetts government.", "difficulty": "hard"},
        {"term": "First Continental Congress", "definition": "1774 meeting of colonial delegates coordinating resistance to British rule.", "difficulty": "medium"},
        {"term": "Lexington and Concord", "definition": "April 1775 battles that marked the start of armed conflict between colonists and Britain.", "difficulty": "medium"},
        {"term": "Second Continental Congress", "definition": "Body that managed the war effort and eventually adopted the Declaration of Independence.", "difficulty": "medium"},
        {"term": "Olive Branch Petition", "definition": "1775 attempt by colonists to reconcile with King George III before full independence.", "difficulty": "hard"},
        {"term": "Common Sense", "definition": "1776 pamphlet by Thomas Paine arguing for colonial independence.", "difficulty": "medium"},
        {"term": "Declaration of Independence", "definition": "Document asserting colonial freedom and listing grievances against the British crown.", "difficulty": "easy"},
    ]),
    "ss_us_hist_american_revolution_set2": make_term_alignment_questions([
        {"term": "Bunker Hill", "definition": "1775 battle demonstrating colonial resolve despite a British victory.", "difficulty": "medium"},
        {"term": "Trenton", "definition": "1776 surprise attack where Washington crossed the Delaware and captured Hessian forces.", "difficulty": "medium"},
        {"term": "Saratoga", "definition": "1777 American victory that convinced France to join the war as an ally.", "difficulty": "medium"},
        {"term": "Valley Forge", "definition": "Winter encampment where the Continental Army endured hardship but emerged better trained.", "difficulty": "medium"},
        {"term": "Marquis de Lafayette", "definition": "French nobleman who provided military leadership and support to Washington.", "difficulty": "medium"},
        {"term": "Friedrich von Steuben", "definition": "Prussian officer who trained American troops at Valley Forge.", "difficulty": "medium"},
        {"term": "Yorktown", "definition": "1781 siege where American and French forces defeated Cornwallis, ending major fighting.", "difficulty": "medium"},
        {"term": "Treaty of Paris 1783", "definition": "Agreement recognizing American independence and setting new national boundaries.", "difficulty": "medium"},
        {"term": "Hessians", "definition": "German soldiers hired by Britain to fight against the colonists.", "difficulty": "easy"},
        {"term": "Privateers", "definition": "Privately owned ships authorized to attack enemy vessels during the war.", "difficulty": "hard"},
        {"term": "Guerrilla tactics", "definition": "Hit-and-run fighting methods used by militias in the southern campaign.", "difficulty": "medium"},
        {"term": "Continental Army", "definition": "Military force established by the Second Continental Congress to fight Britain.", "difficulty": "easy"},
    ]),
    "ss_us_hist_american_revolution_set3": make_term_alignment_questions([
        {"term": "Patriots", "definition": "Colonists who supported independence from Britain.", "difficulty": "easy"},
        {"term": "Loyalists", "definition": "Colonists who remained faithful to the British crown during the war.", "difficulty": "easy"},
        {"term": "Republicanism", "definition": "Political philosophy emphasizing civic virtue and elected representation.", "difficulty": "medium"},
        {"term": "Natural rights", "definition": "Belief that all people are born with inherent rights such as life and liberty.", "difficulty": "medium"},
        {"term": "Social contract", "definition": "Idea that governments derive legitimacy from the consent of the governed.", "difficulty": "medium"},
        {"term": "Diplomatic recognition", "definition": "Formal acknowledgment by other nations of American independence.", "difficulty": "hard"},
        {"term": "Articles of Confederation", "definition": "First U.S. governing document creating a weak central government.", "difficulty": "medium"},
        {"term": "Northwest Ordinance", "definition": "1787 law setting procedures for admitting new states and banning slavery north of the Ohio River.", "difficulty": "hard"},
        {"term": "Treaty of Alliance", "definition": "1778 agreement between the United States and France providing military support.", "difficulty": "hard"},
        {"term": "Inflation", "definition": "Economic problem faced during the war as paper money lost value.", "difficulty": "medium"},
        {"term": "Women in the Revolution", "definition": "Role of figures such as Abigail Adams or camp followers supporting the war effort.", "difficulty": "medium"},
        {"term": "Free African Americans", "definition": "Individuals who fought for both sides hoping to gain freedom or civil rights.", "difficulty": "medium"},
    ]),
    "ss_us_hist_early_republic_set1": make_term_alignment_questions([
        {"term": "Articles of Confederation", "definition": "First U.S. framework that created a weak central government with limited powers.", "difficulty": "medium"},
        {"term": "Shays' Rebellion", "definition": "1786 uprising of Massachusetts farmers protesting debt and taxation, highlighting weaknesses of the Articles.", "difficulty": "hard"},
        {"term": "Constitutional Convention", "definition": "1787 meeting in Philadelphia where delegates drafted the U.S. Constitution.", "difficulty": "medium"},
        {"term": "Great Compromise", "definition": "Agreement creating a bicameral legislature with proportional representation in the House and equal representation in the Senate.", "difficulty": "medium"},
        {"term": "Three-Fifths Compromise", "definition": "Decision to count enslaved individuals as partial population for representation and taxation.", "difficulty": "hard"},
        {"term": "Federalists", "definition": "Supporters of ratifying the Constitution and a stronger national government.", "difficulty": "medium"},
        {"term": "Anti-Federalists", "definition": "Opponents of the Constitution who demanded a Bill of Rights to protect liberties.", "difficulty": "medium"},
        {"term": "Federalist Papers", "definition": "Series of essays defending the Constitution written by Hamilton, Madison, and Jay.", "difficulty": "hard"},
        {"term": "Bill of Rights", "definition": "First ten amendments to the Constitution guaranteeing individual freedoms.", "difficulty": "easy"},
        {"term": "Ratification", "definition": "Formal approval by the states required to adopt the Constitution.", "difficulty": "medium"},
        {"term": "Separation of powers", "definition": "Division of government authority among legislative, executive, and judicial branches.", "difficulty": "medium"},
        {"term": "Checks and balances", "definition": "System ensuring each branch can limit the powers of the others.", "difficulty": "medium"},
    ]),
    "ss_us_hist_early_republic_set2": make_term_alignment_questions([
        {"term": "George Washington", "definition": "First president who established many precedents for the executive branch.", "difficulty": "easy"},
        {"term": "Cabinet", "definition": "Group of advisors heading executive departments who assist the president.", "difficulty": "medium"},
        {"term": "Hamilton's financial plan", "definition": "Program to assume state debts, create a national bank, and support manufacturing.", "difficulty": "hard"},
        {"term": "National Bank", "definition": "Institution proposed by Hamilton to stabilize the economy and manage credit.", "difficulty": "medium"},
        {"term": "Whiskey Rebellion", "definition": "1794 protest of a federal excise tax suppressed by Washington's militia, proving federal authority.", "difficulty": "medium"},
        {"term": "Neutrality Proclamation", "definition": "1793 statement declaring U.S. neutrality in the conflict between Britain and France.", "difficulty": "medium"},
        {"term": "Jay's Treaty", "definition": "1794 agreement with Britain resolving outstanding issues from the Revolutionary War.", "difficulty": "hard"},
        {"term": "Pinckney's Treaty", "definition": "1795 pact with Spain granting U.S. navigation rights on the Mississippi River.", "difficulty": "medium"},
        {"term": "Political parties", "definition": "Organized groups such as Federalists and Democratic-Republicans competing for power.", "difficulty": "medium"},
        {"term": "John Adams", "definition": "Second president who faced challenges such as the XYZ Affair and alien laws.", "difficulty": "medium"},
        {"term": "XYZ Affair", "definition": "1797 diplomatic incident with France leading to calls for war.", "difficulty": "hard"},
        {"term": "Alien and Sedition Acts", "definition": "1798 laws restricting immigration and limiting criticism of the government.", "difficulty": "hard"},
    ]),
    "ss_us_hist_early_republic_set3": make_term_alignment_questions([
        {"term": "Thomas Jefferson", "definition": "Third president who championed agrarian democracy and limited government.", "difficulty": "medium"},
        {"term": "Louisiana Purchase", "definition": "1803 acquisition doubling U.S. territory by buying land from France.", "difficulty": "medium"},
        {"term": "Lewis and Clark Expedition", "definition": "Journey exploring the Louisiana Territory and mapping routes to the Pacific.", "difficulty": "medium"},
        {"term": "Embargo Act", "definition": "1807 law banning U.S. trade with foreign nations to avoid war.", "difficulty": "hard"},
        {"term": "War Hawks", "definition": "Congressional leaders who pushed for war against Britain leading up to 1812.", "difficulty": "medium"},
        {"term": "War of 1812", "definition": "Conflict between the United States and Britain over trade restrictions and impressment.", "difficulty": "medium"},
        {"term": "Treaty of Ghent", "definition": "1814 agreement ending the War of 1812 without territorial changes.", "difficulty": "medium"},
        {"term": "Hartford Convention", "definition": "Meeting of New England Federalists opposing the war and discussing constitutional amendments.", "difficulty": "hard"},
        {"term": "Era of Good Feelings", "definition": "Period of national unity and one-party politics following the War of 1812.", "difficulty": "medium"},
        {"term": "Monroe Doctrine", "definition": "1823 policy opposing European colonization in the Western Hemisphere.", "difficulty": "medium"},
        {"term": "Missouri Compromise", "definition": "1820 agreement admitting Missouri as a slave state and Maine as free while banning slavery north of 36°30'.", "difficulty": "hard"},
        {"term": "Judicial nationalism", "definition": "Trend of Supreme Court decisions strengthening federal authority during the early 1800s.", "difficulty": "hard"},
    ]),
    "ss_us_hist_westward_expansion_set1": make_term_alignment_questions([
        {"term": "Manifest Destiny", "definition": "Belief that the United States was destined to expand across the continent.", "difficulty": "medium"},
        {"term": "Louisiana Purchase", "definition": "1803 land acquisition doubling the size of the United States.", "difficulty": "medium"},
        {"term": "Lewis and Clark", "definition": "Explorers who mapped the West and established relations with Native nations.", "difficulty": "medium"},
        {"term": "Zebulon Pike", "definition": "Explorer who led expeditions into the Southwest and Rockies.", "difficulty": "hard"},
        {"term": "Oregon Trail", "definition": "Route taken by thousands of settlers moving to the Pacific Northwest.", "difficulty": "medium"},
        {"term": "Fifty-Four Forty or Fight", "definition": "Slogan demanding full control of the Oregon Territory from Britain.", "difficulty": "hard"},
        {"term": "Texas Annexation", "definition": "1845 incorporation of the Republic of Texas into the United States.", "difficulty": "medium"},
        {"term": "Alamo", "definition": "1836 battle in Texas where defenders resisted Mexican forces before being overrun.", "difficulty": "medium"},
        {"term": "Mexican-American War", "definition": "Conflict from 1846 to 1848 resulting in significant territorial gains for the United States.", "difficulty": "medium"},
        {"term": "Treaty of Guadalupe Hidalgo", "definition": "1848 agreement transferring the Southwest and California to the United States.", "difficulty": "medium"},
        {"term": "Gadsden Purchase", "definition": "1853 acquisition of land in present-day Arizona and New Mexico for a southern railroad route.", "difficulty": "hard"},
        {"term": "Mormon migration", "definition": "Movement led by Brigham Young establishing settlements in Utah Territory.", "difficulty": "medium"},
    ]),
    "ss_us_hist_westward_expansion_set2": make_term_alignment_questions([
        {"term": "California Gold Rush", "definition": "Mass migration beginning in 1848 after discovery of gold at Sutter's Mill.", "difficulty": "medium"},
        {"term": "Forty-Niners", "definition": "Prospectors who traveled to California in 1849 seeking gold.", "difficulty": "easy"},
        {"term": "Homestead Act", "definition": "1862 law granting settlers 160 acres of public land if they improved it.", "difficulty": "medium"},
        {"term": "Pacific Railway Act", "definition": "Legislation that supported construction of the transcontinental railroad.", "difficulty": "medium"},
        {"term": "Transcontinental Railroad", "definition": "Rail line completed in 1869 connecting the Atlantic and Pacific coasts.", "difficulty": "medium"},
        {"term": "Boomtown", "definition": "Rapidly growing settlement that sprang up near mining sites.", "difficulty": "easy"},
        {"term": "Open range", "definition": "Vast public lands used by ranchers to graze cattle without fences.", "difficulty": "medium"},
        {"term": "Chisholm Trail", "definition": "Route used to drive cattle from Texas ranches to Kansas railheads.", "difficulty": "medium"},
        {"term": "Cowboys", "definition": "Workers who herded cattle across the Plains to market.", "difficulty": "easy"},
        {"term": "Barbed wire", "definition": "Invention that allowed farmers to fence land, ending the open range system.", "difficulty": "medium"},
        {"term": "Sod houses", "definition": "Homes built from prairie turf by settlers lacking timber.", "difficulty": "medium"},
        {"term": "Exodusters", "definition": "African American migrants who left the South for Kansas and the West after Reconstruction.", "difficulty": "hard"},
    ]),
    "ss_us_hist_westward_expansion_set3": make_term_alignment_questions([
        {"term": "Indian Removal Act", "definition": "1830 law authorizing the forced relocation of Native American tribes east of the Mississippi.", "difficulty": "hard"},
        {"term": "Trail of Tears", "definition": "Forced march that relocated the Cherokee Nation to Indian Territory with great loss of life.", "difficulty": "medium"},
        {"term": "Reservation system", "definition": "Policy confining Native peoples to specific areas controlled by the government.", "difficulty": "hard"},
        {"term": "Sand Creek Massacre", "definition": "1864 attack in Colorado where militia killed Cheyenne and Arapaho villagers.", "difficulty": "hard"},
        {"term": "Battle of Little Bighorn", "definition": "1876 victory for the Lakota and Cheyenne over Custer's forces.", "difficulty": "medium"},
        {"term": "Wounded Knee", "definition": "1890 confrontation in South Dakota resulting in the deaths of hundreds of Lakota.", "difficulty": "medium"},
        {"term": "Assimilation", "definition": "Government strategy encouraging Native peoples to adopt Euro-American culture.", "difficulty": "hard"},
        {"term": "Dawes Act", "definition": "1887 law dividing tribal lands into individual allotments to promote farming.", "difficulty": "hard"},
        {"term": "Buffalo destruction", "definition": "Mass slaughter of Plains bison that devastated Native economies.", "difficulty": "medium"},
        {"term": "Sitting Bull", "definition": "Lakota leader who resisted U.S. policies and fought at Little Bighorn.", "difficulty": "medium"},
        {"term": "Chief Joseph", "definition": "Leader of the Nez Perce who attempted to flee to Canada to avoid relocation.", "difficulty": "medium"},
        {"term": "Ghost Dance", "definition": "Religious movement promising the restoration of Native lands and disappearance of settlers.", "difficulty": "hard"},
    ]),
    "ss_us_hist_civil_war_set1": make_term_alignment_questions([
        {"term": "Compromise of 1850", "definition": "Series of laws admitting California as a free state and strengthening the Fugitive Slave Act.", "difficulty": "hard"},
        {"term": "Fugitive Slave Act", "definition": "Law requiring citizens to help return escaped enslaved people to owners.", "difficulty": "medium"},
        {"term": "Kansas-Nebraska Act", "definition": "1854 law allowing settlers to decide on slavery through popular sovereignty.", "difficulty": "hard"},
        {"term": "Popular sovereignty", "definition": "Policy letting residents of a territory vote on whether to permit slavery.", "difficulty": "medium"},
        {"term": "Bleeding Kansas", "definition": "Violent conflict between proslavery and antislavery settlers in the Kansas Territory.", "difficulty": "medium"},
        {"term": "Dred Scott decision", "definition": "1857 Supreme Court ruling declaring African Americans were not citizens and Congress could not ban slavery in territories.", "difficulty": "hard"},
        {"term": "John Brown's Raid", "definition": "1859 attempt to seize Harpers Ferry arsenal to start a slave uprising.", "difficulty": "medium"},
        {"term": "Election of 1860", "definition": "Presidential contest won by Abraham Lincoln, prompting Southern secession.", "difficulty": "medium"},
        {"term": "Secession", "definition": "Act of Southern states leaving the Union to form the Confederacy.", "difficulty": "medium"},
        {"term": "Confederate States of America", "definition": "Government formed by seceding Southern states in 1861.", "difficulty": "medium"},
        {"term": "States' rights", "definition": "Argument that states could nullify federal laws they considered unconstitutional.", "difficulty": "medium"},
        {"term": "Uncle Tom's Cabin", "definition": "Harriet Beecher Stowe's novel that increased Northern opposition to slavery.", "difficulty": "medium"},
    ]),
    "ss_us_hist_civil_war_set2": make_term_alignment_questions([
        {"term": "Fort Sumter", "definition": "April 1861 attack that marked the beginning of the Civil War.", "difficulty": "medium"},
        {"term": "Anaconda Plan", "definition": "Union strategy to blockade Southern ports and control the Mississippi River.", "difficulty": "medium"},
        {"term": "First Battle of Bull Run", "definition": "1861 Confederate victory showing the war would be longer than expected.", "difficulty": "medium"},
        {"term": "Battle of Antietam", "definition": "1862 clash in Maryland that became the bloodiest single day of the war.", "difficulty": "medium"},
        {"term": "Emancipation Proclamation", "definition": "1863 order freeing enslaved people in Confederate-held territories.", "difficulty": "medium"},
        {"term": "54th Massachusetts Regiment", "definition": "African American unit that gained fame for its attack on Fort Wagner.", "difficulty": "hard"},
        {"term": "Battle of Gettysburg", "definition": "1863 Union victory in Pennsylvania considered a turning point of the war.", "difficulty": "medium"},
        {"term": "Gettysburg Address", "definition": "Speech by Abraham Lincoln redefining the war as a struggle for equality and unity.", "difficulty": "medium"},
        {"term": "Siege of Vicksburg", "definition": "Union campaign capturing a key Mississippi River city in 1863.", "difficulty": "medium"},
        {"term": "William T. Sherman", "definition": "Union general known for his March to the Sea and total war tactics.", "difficulty": "medium"},
        {"term": "Total war", "definition": "Strategy targeting not only opposing armies but also resources and infrastructure.", "difficulty": "hard"},
        {"term": "Appomattox Court House", "definition": "Virginia site where Robert E. Lee surrendered to Ulysses S. Grant in 1865.", "difficulty": "medium"},
    ]),
    "ss_us_hist_civil_war_set3": make_term_alignment_questions([
        {"term": "Reconstruction", "definition": "Period from 1865 to 1877 focused on rebuilding the South and integrating freed people.", "difficulty": "medium"},
        {"term": "Freedmen's Bureau", "definition": "Agency providing education, food, and legal help to formerly enslaved people.", "difficulty": "medium"},
        {"term": "13th Amendment", "definition": "Constitutional change abolishing slavery in the United States.", "difficulty": "medium"},
        {"term": "14th Amendment", "definition": "Amendment granting citizenship and equal protection under the law.", "difficulty": "hard"},
        {"term": "15th Amendment", "definition": "Amendment prohibiting denial of voting rights based on race or previous condition of servitude.", "difficulty": "hard"},
        {"term": "Black Codes", "definition": "Southern laws designed to restrict the freedom of African Americans after the war.", "difficulty": "medium"},
        {"term": "Sharecropping", "definition": "System where farmers worked land owned by others in return for a share of the crop.", "difficulty": "medium"},
        {"term": "Ku Klux Klan", "definition": "White supremacist organization that used violence to oppose Reconstruction.", "difficulty": "hard"},
        {"term": "Radical Republicans", "definition": "Congressional leaders who pushed for strict Reconstruction policies and civil rights.", "difficulty": "medium"},
        {"term": "Military Reconstruction Act", "definition": "1867 law dividing the South into military districts to enforce federal policies.", "difficulty": "hard"},
        {"term": "Compromise of 1877", "definition": "Agreement ending Reconstruction by withdrawing federal troops from the South.", "difficulty": "hard"},
        {"term": "Poll tax", "definition": "Fee charged to voters that was used to disenfranchise African Americans.", "difficulty": "medium"},
    ]),
    "ss_us_hist_foundations": make_term_alignment_questions([
        {"term": "Columbian Exchange", "definition": "Transfer of plants, animals, people, and diseases between the Old and New Worlds after 1492.", "difficulty": "medium"},
        {"term": "Spanish missions", "definition": "Religious settlements established to convert Indigenous peoples in the Americas.", "difficulty": "medium"},
        {"term": "Encomienda system", "definition": "Spanish labor arrangement granting colonists control over Indigenous workers.", "difficulty": "hard"},
        {"term": "Roanoke", "definition": "Failed English colony founded in the 1580s on the coast of present-day North Carolina.", "difficulty": "medium"},
        {"term": "Headright system", "definition": "Virginia policy granting land to settlers who paid for their own or others' passage.", "difficulty": "hard"},
        {"term": "Bering Land Bridge", "definition": "Route early peoples used to migrate from Asia to North America during the Ice Age.", "difficulty": "medium"},
        {"term": "Iroquois Confederacy", "definition": "Alliance of Native nations in the Northeast that maintained a powerful council.", "difficulty": "medium"},
        {"term": "Pequot War", "definition": "1630s conflict between New England colonists and Pequot people resulting in the tribe's defeat.", "difficulty": "hard"},
        {"term": "King Philip's War", "definition": "1675 Native uprising led by Metacom against New England colonists.", "difficulty": "medium"},
        {"term": "Navigation Acts", "definition": "British trade laws regulating colonial commerce for mercantilist goals.", "difficulty": "hard"},
        {"term": "Dominion of New England", "definition": "Short-lived merger of several colonies under royal governor Edmund Andros in the 1680s.", "difficulty": "hard"},
        {"term": "Glorious Revolution", "definition": "1688 event that replaced England's monarch and inspired colonial demands for rights.", "difficulty": "medium"},
    ]),
    "us_history_revolution_quiz_1": make_term_alignment_questions([
        {"term": "Sugar Act", "definition": "1764 law lowering duties but increasing enforcement on molasses imports.", "difficulty": "medium"},
        {"term": "Quartering Act", "definition": "Requirement that colonists provide housing for British troops stationed in America.", "difficulty": "medium"},
        {"term": "Declaratory Act", "definition": "1766 statement asserting Parliament's authority to tax the colonies in all cases.", "difficulty": "hard"},
        {"term": "Townshend Acts", "definition": "1767 taxes on glass, lead, paint, and tea used to raise revenue for colonial administration.", "difficulty": "medium"},
        {"term": "Nonimportation agreements", "definition": "Colonial pledges to boycott British goods in protest of taxes.", "difficulty": "medium"},
        {"term": "Committees of Correspondence", "definition": "Networks sharing information and coordinating resistance between colonies.", "difficulty": "medium"},
        {"term": "Gaspee Affair", "definition": "1772 incident where colonists burned a British customs ship off Rhode Island.", "difficulty": "hard"},
        {"term": "Tea monopoly", "definition": "Privilege granted to the British East India Company leading to colonial protests.", "difficulty": "medium"},
        {"term": "Intolerable Acts", "definition": "Punitive laws closing Boston Harbor and altering colonial governance after the Tea Party.", "difficulty": "hard"},
        {"term": "Quebec Act", "definition": "1774 law extending Canada's boundaries and tolerating Catholicism, angering colonists.", "difficulty": "hard"},
        {"term": "First Continental Congress", "definition": "1774 assembly that coordinated colonial response to British policies.", "difficulty": "medium"},
        {"term": "Lexington alarm", "definition": "Paul Revere and others' midnight rides warning militia of British troop movements.", "difficulty": "medium"},
    ]),
    "us_history_revolution_quiz_2": make_term_alignment_questions([
        {"term": "George Washington", "definition": "Commander of the Continental Army who led forces to victory over Britain.", "difficulty": "easy"},
        {"term": "Benedict Arnold", "definition": "American officer who later defected to the British during the war.", "difficulty": "medium"},
        {"term": "Nathan Hale", "definition": "Patriot spy captured and executed by the British, remembered for his quote about regret.", "difficulty": "hard"},
        {"term": "Battle of Bunker Hill", "definition": "1775 clash near Boston showing colonists could challenge British troops.", "difficulty": "medium"},
        {"term": "Battle of Long Island", "definition": "1776 defeat where Washington's army escaped across the East River.", "difficulty": "hard"},
        {"term": "Battle of Saratoga", "definition": "Turning point battle convincing France to ally with the Americans.", "difficulty": "medium"},
        {"term": "Valley Forge", "definition": "Winter camp where Baron von Steuben trained Washington's soldiers.", "difficulty": "medium"},
        {"term": "Battle of Cowpens", "definition": "1781 American victory in South Carolina using a double envelopment tactic.", "difficulty": "hard"},
        {"term": "Battle of Yorktown", "definition": "Final major battle where British General Cornwallis surrendered.", "difficulty": "medium"},
        {"term": "James Armistead Lafayette", "definition": "Enslaved spy who provided intelligence helping the American cause.", "difficulty": "hard"},
        {"term": "Molly Pitcher", "definition": "Nickname for women who aided artillery crews, symbolized by Mary Ludwig Hays.", "difficulty": "medium"},
        {"term": "Francis Marion", "definition": "South Carolina leader known as the 'Swamp Fox' for guerrilla tactics.", "difficulty": "medium"},
    ]),
    "us_history_revolution_quiz_3": make_term_alignment_questions([
        {"term": "Republican motherhood", "definition": "Expectation that women would raise children to be virtuous citizens in the new republic.", "difficulty": "medium"},
        {"term": "Liberty", "definition": "Core ideal emphasizing freedom from oppressive government control.", "difficulty": "easy"},
        {"term": "Equality", "definition": "Principle that all people deserve similar political rights and opportunities.", "difficulty": "medium"},
        {"term": "Consent of the governed", "definition": "Idea that governments derive power from the agreement of the people.", "difficulty": "medium"},
        {"term": "Natural rights", "definition": "Belief in inherent human rights such as life, liberty, and property.", "difficulty": "medium"},
        {"term": "Civic virtue", "definition": "Citizen commitment to the common good above personal interests.", "difficulty": "medium"},
        {"term": "Republic", "definition": "Government in which citizens elect representatives to make decisions.", "difficulty": "easy"},
        {"term": "Loyalist exodus", "definition": "Departure of colonists loyal to Britain who faced persecution after the war.", "difficulty": "medium"},
        {"term": "Abolition movement", "definition": "Efforts during and after the Revolution to end slavery in Northern states.", "difficulty": "medium"},
        {"term": "State constitutions", "definition": "Documents adopted by colonies-turned-states outlining rights and limits on power.", "difficulty": "medium"},
        {"term": "Property requirements", "definition": "Voting qualifications that required land ownership in many early states.", "difficulty": "hard"},
        {"term": "Disestablishment", "definition": "Process of ending government support for official churches in the new nation.", "difficulty": "hard"},
    ]),
    "ss_econ_foundations_set1": make_term_alignment_questions([
        {"term": "Scarcity", "definition": "Basic economic problem of limited resources and unlimited wants.", "difficulty": "easy"},
        {"term": "Opportunity cost", "definition": "Value of the next best alternative sacrificed when making a choice.", "difficulty": "medium"},
        {"term": "Supply", "definition": "Quantity of a good or service producers are willing to offer at different prices.", "difficulty": "medium"},
        {"term": "Demand", "definition": "Quantity of a good or service consumers are willing and able to buy at various prices.", "difficulty": "medium"},
        {"term": "Market equilibrium", "definition": "Point where supply equals demand and prices stabilize.", "difficulty": "hard"},
        {"term": "Incentive", "definition": "Reward or penalty that influences the choices people make.", "difficulty": "easy"},
        {"term": "Entrepreneur", "definition": "Individual who organizes productive resources and takes risks to create goods or services.", "difficulty": "medium"},
        {"term": "Factors of production", "definition": "Economic resources of land, labor, capital, and entrepreneurship.", "difficulty": "medium"},
        {"term": "Mixed economy", "definition": "System combining market forces with government involvement.", "difficulty": "medium"},
        {"term": "Traditional economy", "definition": "System in which customs and traditions determine economic decisions.", "difficulty": "medium"},
        {"term": "Command economy", "definition": "System where government planners make most economic decisions.", "difficulty": "medium"},
        {"term": "Gross domestic product", "definition": "Total value of goods and services produced within a country in a given year.", "difficulty": "hard"},
    ]),
    "ss_geo_map_skills_set1": make_term_alignment_questions([
        {"term": "Latitude", "definition": "Imaginary lines measuring distance north or south of the Equator.", "difficulty": "easy"},
        {"term": "Longitude", "definition": "Imaginary lines measuring distance east or west of the Prime Meridian.", "difficulty": "easy"},
        {"term": "Scale", "definition": "Relationship between distance on a map and the actual distance on Earth.", "difficulty": "medium"},
        {"term": "Legend", "definition": "Map feature explaining symbols and colors used to represent information.", "difficulty": "easy"},
        {"term": "Compass rose", "definition": "Diagram on a map showing cardinal and intermediate directions.", "difficulty": "easy"},
        {"term": "Topographic map", "definition": "Map displaying elevation and landform features through contour lines.", "difficulty": "medium"},
        {"term": "Thematic map", "definition": "Map focusing on a specific subject such as population or climate.", "difficulty": "medium"},
        {"term": "GIS", "definition": "Computer system that collects, stores, and analyzes geographic data.", "difficulty": "hard"},
        {"term": "GPS", "definition": "Satellite-based navigation system that determines precise locations on Earth.", "difficulty": "medium"},
        {"term": "Projection", "definition": "Method of representing Earth's curved surface on a flat map.", "difficulty": "hard"},
        {"term": "Relative location", "definition": "Description of a place in relation to other locations.", "difficulty": "medium"},
        {"term": "Absolute location", "definition": "Exact position of a place given by coordinates of latitude and longitude.", "difficulty": "medium"},
    ]),
})
